"use client"

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react"
import { Boxes, ClipboardList, Factory, FolderKanban, Loader2, Plus, Search, Wrench } from "lucide-react"
import { toast } from "sonner"
import { PageHeader } from "@/components/shared/page-header"
import { ConfirmActionDialog } from "@/components/shared/confirm-action-dialog"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Textarea } from "@/components/ui/textarea"
import { useAuthStore } from "@/stores/auth-store"
import { useAppStore } from "@/stores/app-store"

type Version = { id: string; revision: string; status: string; _count?: { lines: number }; lines?: BomLine[] }
type Bom = { id: string; name: string; item: { id?: string; code: string; title: string; unit?: string }; projectTag?: { id: string; name: string } | null; versions: Version[] }
type BomLine = { id: string; sourceLineKey: string; quantity: string; unit?: string | null; notes?: string | null; sortOrder: number; item: { id: string; code: string; title: string; unit: string }; parentLine?: { id: string; sourceLineKey: string } | null; applicability: Array<{ tag: string; quantity: string }>; consumptionRouteStep?: { id: string } | null }
type Definitions = { profiles: Array<{ id: string }>; boms: Bom[]; routes: Array<{ id: string; versions: Version[] }>; operations: Ref[]; workCenters: Ref[]; resources: Ref[] }
type Ref = { id: string; code: string; name: string; status: string }
type Rollup = { project: { id: string; name: string }; category: { id: string | null; name: string }; item: { id: string; code: string; title: string; unit: string }; quantityPerBuild: string; bomNames: string[] }
const label = (value: string) => value.toLowerCase().replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase())
async function api<T>(url: string, init?: RequestInit): Promise<T> { const response = await fetch(url, init), body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || "Request failed"); return body }

export function ManufacturingPage() {
  const page = useAppStore(state => state.currentPage), id = useAppStore(state => state.selectedEntityId), navigate = useAppStore(state => state.navigate)
  const canManage = useAuthStore(state => state.user?.permissions.includes("manufacturing.definitions.manage") ?? false)
  const [data, setData] = useState<Definitions | null>(null), [loading, setLoading] = useState(true)
  const load = useCallback(async () => { setLoading(true); try { setData(await api<Definitions>("/api/v1/manufacturing/definitions")) } catch (error) { toast.error(error instanceof Error ? error.message : "Could not load manufacturing") } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  if (loading) return <Loading />
  if (!data) return <Empty title="Manufacturing could not be loaded" action={<Button onClick={() => void load()}>Try again</Button>} />
  if (page === "manufacturing-bom-detail") return <BomDetail bomId={id} canManage={canManage} back={() => navigate("manufacturing-boms")} changed={load} />
  if (page === "manufacturing-project-detail") return <ProjectDetail projectId={id} boms={data.boms} back={() => navigate("manufacturing-projects")} openBom={bomId => navigate("manufacturing-bom-detail", bomId)} />
  if (page === "manufacturing-boms") return <BomRegister boms={data.boms} open={bomId => navigate("manufacturing-bom-detail", bomId)} />
  if (page === "manufacturing-projects") return <ProjectRegister boms={data.boms} open={projectId => navigate("manufacturing-project-detail", projectId)} />
  if (page === "manufacturing-planning") return <Planning />
  return <Overview data={data} canManage={canManage} navigate={navigate} changed={load} />
}

function Overview({ data, canManage, navigate, changed }: { data: Definitions; canManage: boolean; navigate: (page: "manufacturing-boms" | "manufacturing-projects" | "manufacturing-planning") => void; changed: () => void }) {
  const [kind, setKind] = useState<"operation" | "work-center" | "resource" | null>(null), versions = data.boms.flatMap(bom => bom.versions)
  return <div className="space-y-6"><PageHeader title="Manufacturing" description="Project BOM definitions, production-readiness data, and planning material roll-ups." icon={Factory}>{canManage && <Button onClick={() => setKind("operation")}><Plus className="mr-2 size-4"/>New operation</Button>}</PageHeader>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Active BOMs" value={versions.filter(version => version.status === "ACTIVE").length} detail="Accepted definitions"/><Metric label="Draft BOMs" value={versions.filter(version => version.status === "DRAFT").length} detail="Review work in progress"/><Metric label="Projects" value={new Set(data.boms.flatMap(bom => bom.projectTag ? [bom.projectTag.id] : [])).size} detail="With manufacturing definitions"/><Metric label="Production readiness" value={data.routes.length ? "Configured" : "Definitions only"} detail={data.routes.length ? `${data.routes.length} routes available` : "Routes and resources are not configured"}/></div>
    <div className="grid gap-4 lg:grid-cols-3"><Action icon={<ClipboardList className="size-5"/>} title="BOM register" description="Separate Draft and Active definitions, then open a shareable spreadsheet workspace." action="Open BOMs" onClick={() => navigate("manufacturing-boms")}/><Action icon={<FolderKanban className="size-5"/>} title="Project views" description="See each project’s outputs, BOM revisions and future cycle context." action="Open projects" onClick={() => navigate("manufacturing-projects")}/><Action icon={<Boxes className="size-5"/>} title="Production planning" description="Consolidate active BOM material requirements by project and category." action="Open planning" onClick={() => navigate("manufacturing-planning")}/></div>
    <div className="grid gap-4 lg:grid-cols-3"><RefCard title="Operations" rows={data.operations} onAdd={canManage ? () => setKind("operation") : undefined}/><RefCard title="Work centers" rows={data.workCenters} onAdd={canManage ? () => setKind("work-center") : undefined}/><RefCard title="Machines & equipment" rows={data.resources} onAdd={canManage ? () => setKind("resource") : undefined}/></div><ReferenceDialog kind={kind} close={() => setKind(null)} saved={changed}/>
  </div>
}

function BomRegister({ boms, open }: { boms: Bom[]; open: (id: string) => void }) {
  const [query, setQuery] = useState(""), [project, setProject] = useState("all"), [status, setStatus] = useState("all")
  const projects = useMemo(() => [...new Map(boms.flatMap(bom => bom.projectTag ? [[bom.projectTag.id, bom.projectTag] as const] : [])).values()].sort((a,b) => a.name.localeCompare(b.name)), [boms])
  const rows = useMemo(() => boms.flatMap(bom => bom.versions.map(version => ({ bom, version }))).filter(({ bom, version }) => (project === "all" || bom.projectTag?.id === project) && (status === "all" || version.status === status) && `${bom.name} ${bom.item.code} ${bom.item.title}`.toLowerCase().includes(query.toLowerCase())), [boms, project, status, query])
  return <div className="space-y-6"><PageHeader title="BOM register" description="Draft and active definitions stay separate. Open a BOM for its audit-ready grid." icon={ClipboardList}/><Card><CardContent className="grid gap-3 pt-6 md:grid-cols-[1fr_14rem_12rem]"><div className="relative"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input className="pl-9" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search BOM or output"/></div><Select value={project} onValueChange={setProject}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All projects</SelectItem>{projects.map(row => <SelectItem key={row.id} value={row.id}>{row.name}</SelectItem>)}</SelectContent></Select><Select value={status} onValueChange={setStatus}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All states</SelectItem><SelectItem value="DRAFT">Draft only</SelectItem><SelectItem value="ACTIVE">Active only</SelectItem><SelectItem value="RETIRED">Retired only</SelectItem></SelectContent></Select></CardContent></Card><Card><CardContent className="p-0"><Table><TableHeader><TableRow className="bg-muted/40"><TableHead className="pl-5">Project / BOM</TableHead><TableHead>Output item</TableHead><TableHead>Revision</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Lines</TableHead><TableHead className="pr-5"/></TableRow></TableHeader><TableBody>{rows.map(({bom,version}) => <TableRow key={version.id}><TableCell className="pl-5"><div className="font-medium">{bom.name}</div><div className="text-xs text-muted-foreground">{bom.projectTag?.name || "Shared"}</div></TableCell><TableCell><div className="font-medium">{bom.item.title}</div><div className="font-mono text-xs text-muted-foreground">{bom.item.code}</div></TableCell><TableCell className="font-mono text-xs">{version.revision}</TableCell><TableCell><State value={version.status}/></TableCell><TableCell className="text-right tabular-nums">{version._count?.lines || 0}</TableCell><TableCell className="pr-5 text-right"><Button size="sm" variant="outline" onClick={() => open(bom.id)}>Open</Button></TableCell></TableRow>)}{!rows.length && <TableRow><TableCell colSpan={6} className="py-12 text-center text-muted-foreground">No BOM revisions match these filters.</TableCell></TableRow>}</TableBody></Table></CardContent></Card></div>
}

function BomDetail({ bomId, canManage, back, changed }: { bomId: string | null; canManage: boolean; back: () => void; changed: () => void }) {
  const [bom, setBom] = useState<Bom | null>(null), [loading, setLoading] = useState(true), [activation, setActivation] = useState<Version | null>(null), [busy, setBusy] = useState(false)
  const load = useCallback(async () => { if (!bomId) return; setLoading(true); try { setBom((await api<{bom: Bom}>(`/api/v1/manufacturing/boms/${bomId}`)).bom) } catch (error) { toast.error(error instanceof Error ? error.message : "Could not load BOM") } finally { setLoading(false) } }, [bomId])
  useEffect(() => { void load() }, [load])
  if (!bomId) return <Empty title="No BOM selected" action={<Button onClick={back}>Back to BOM register</Button>}/>
  if (loading) return <Loading/>
  if (!bom) return <Empty title="BOM was not found" action={<Button onClick={back}>Back to BOM register</Button>}/>
  const activate = async () => { if (!activation) return; setBusy(true); try { await api(`/api/v1/manufacturing/bom-versions/${activation.id}/activate`, {method:"POST"}); toast.success("BOM revision activated"); setActivation(null); await load(); changed() } catch (error) { toast.error(error instanceof Error ? error.message : "Could not activate revision") } finally { setBusy(false) } }
  const versions = [...bom.versions].sort((left,right) => ({ACTIVE:0,DRAFT:1,RETIRED:2}[left.status as "ACTIVE"] ?? 3) - ({ACTIVE:0,DRAFT:1,RETIRED:2}[right.status as "ACTIVE"] ?? 3))
  return <div className="space-y-6"><Button variant="ghost" className="-ml-3" onClick={back}>← Back to BOM register</Button><PageHeader title={bom.name} description={`${bom.projectTag?.name || "Shared definition"} · Output ${bom.item.code} — ${bom.item.title}`} icon={ClipboardList}/><div className="grid gap-4 sm:grid-cols-3"><Metric label="Active revisions" value={versions.filter(version => version.status === "ACTIVE").length} detail="Available for new cycles"/><Metric label="Draft revisions" value={versions.filter(version => version.status === "DRAFT").length} detail="Editable review work"/><Metric label="Source rows" value={versions.reduce((total,version) => total + (version.lines?.length || 0),0)} detail="Retained in the version audit trail"/></div>{versions.map(version => <VersionGrid key={version.id} version={version} canManage={canManage} activate={() => setActivation(version)} saved={load}/>) }<ConfirmActionDialog open={Boolean(activation)} onOpenChange={open => !open && setActivation(null)} title="Activate this BOM revision?" description="It becomes the active definition for new manufacturing cycles. Existing cycles remain bound to their original revision." confirmLabel="Activate revision" busy={busy} onConfirm={activate}/></div>
}

function VersionGrid({ version, canManage, activate, saved }: { version: Version; canManage: boolean; activate: () => void; saved: () => Promise<void> }) {
  const [editing,setEditing] = useState(false), lines = version.lines || []
  return <Card><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="flex items-center gap-2 text-base">Revision {version.revision}<State value={version.status}/></CardTitle><p className="mt-1 text-sm text-muted-foreground">{lines.length} source-linked rows. Draft revisions can be corrected in the grid before acceptance.</p></div>{canManage && version.status === "DRAFT" && <div className="flex gap-2"><Button variant="outline" onClick={() => setEditing(value => !value)}>{editing ? "Close editor" : "Edit spreadsheet"}</Button><Button onClick={activate}>Activate after review</Button></div>}</div></CardHeader><CardContent>{editing ? <DraftEditor version={version} saved={async () => {setEditing(false);await saved()}}/> : <TreeTable lines={lines}/>}</CardContent></Card>
}

function TreeTable({ lines }: { lines: BomLine[] }) { const byId = new Map(lines.map(line => [line.id,line])); const depth=(line:BomLine)=>{let count=0,current=line;const seen=new Set<string>();while(current.parentLine&&!seen.has(current.id)){seen.add(current.id);count++;const parent=byId.get(current.parentLine.id);if(!parent)break;current=parent}return count}; return <Table><TableHeader><TableRow className="bg-muted/40"><TableHead>Source</TableHead><TableHead>Component hierarchy</TableHead><TableHead className="text-right">Qty / parent</TableHead><TableHead>Unit</TableHead><TableHead>Applies to</TableHead><TableHead>Source evidence</TableHead></TableRow></TableHeader><TableBody>{lines.map(line => <TableRow key={line.id}><TableCell className="font-mono text-xs">{line.sourceLineKey}</TableCell><TableCell><div className="flex gap-2" style={{paddingLeft:`${depth(line)*18}px`}}><span className="text-muted-foreground">{line.parentLine ? "↳" : "•"}</span><div><div className="font-medium">{line.item.title}</div><div className="font-mono text-xs text-muted-foreground">{line.item.code}</div></div></div></TableCell><TableCell className="text-right tabular-nums">{line.quantity}</TableCell><TableCell>{line.unit || line.item.unit}</TableCell><TableCell className="max-w-52 whitespace-normal">{line.applicability.length ? line.applicability.map(entry=><Badge className="mr-1" key={entry.tag} variant="outline">{entry.tag} × {entry.quantity}</Badge>) : <span className="text-xs text-muted-foreground">All output</span>}</TableCell><TableCell className="max-w-72 whitespace-normal text-xs text-muted-foreground">{line.notes || "—"}</TableCell></TableRow>)}</TableBody></Table> }

function DraftEditor({ version, saved }: { version: Version; saved: () => Promise<void> }) { const [rows,setRows]=useState(() => (version.lines || []).map(line => ({...line,parentSourceLineKey:line.parentLine?.sourceLineKey || ""}))),[saving,setSaving]=useState(false); const update=(index:number,key:"sourceLineKey"|"parentSourceLineKey"|"quantity"|"unit"|"notes",value:string)=>setRows(current=>current.map((line,row)=>row===index?{...line,[key]:value}:line)); const save=async()=>{setSaving(true);try{await api(`/api/v1/manufacturing/bom-versions/${version.id}`,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({lines:rows.map((line,index)=>({sourceLineKey:line.sourceLineKey,parentSourceLineKey:line.parentSourceLineKey||null,itemId:line.item.id,quantity:line.quantity,unit:line.unit||null,notes:line.notes||null,sortOrder:index,consumptionRouteStepId:line.consumptionRouteStep?.id||null,applicability:line.applicability}))})});toast.success("Draft spreadsheet saved");await saved()}catch(error){toast.error(error instanceof Error?error.message:"Could not save draft")}finally{setSaving(false)}};return <div className="space-y-3"><p className="text-sm text-muted-foreground">Save is atomic for the complete Draft revision. This initial editor keeps component identity fixed while allowing Excel-like correction of hierarchy, quantities, units and source evidence.</p><Table><TableHeader><TableRow className="bg-muted/40"><TableHead>Source key</TableHead><TableHead>Parent key</TableHead><TableHead>Component</TableHead><TableHead>Qty</TableHead><TableHead>Unit</TableHead><TableHead>Source evidence</TableHead></TableRow></TableHeader><TableBody>{rows.map((line,index)=><TableRow key={line.id}><TableCell><Input value={line.sourceLineKey} onChange={event=>update(index,"sourceLineKey",event.target.value)}/></TableCell><TableCell><Input value={line.parentSourceLineKey} onChange={event=>update(index,"parentSourceLineKey",event.target.value)} placeholder="Root"/></TableCell><TableCell><div className="font-medium">{line.item.title}</div><div className="font-mono text-xs text-muted-foreground">{line.item.code}</div></TableCell><TableCell><Input inputMode="decimal" value={line.quantity} onChange={event=>update(index,"quantity",event.target.value)}/></TableCell><TableCell><Input value={line.unit || ""} onChange={event=>update(index,"unit",event.target.value)}/></TableCell><TableCell><Textarea value={line.notes || ""} onChange={event=>update(index,"notes",event.target.value)}/></TableCell></TableRow>)}</TableBody></Table><div className="flex justify-end"><Button disabled={saving} onClick={()=>void save()}>{saving&&<Loader2 className="mr-2 size-4 animate-spin"/>}Save Draft revision</Button></div></div> }

function ProjectRegister({ boms, open }: { boms: Bom[]; open: (id:string)=>void }) { const projects=useMemo(()=>[...new Map(boms.flatMap(bom=>bom.projectTag?[[bom.projectTag.id,bom.projectTag] as const]:[])).values()].map(project=>{const scoped=boms.filter(bom=>bom.projectTag?.id===project.id),versions=scoped.flatMap(bom=>bom.versions);return {project,boms:scoped.length,active:versions.filter(version=>version.status==="ACTIVE").length,draft:versions.filter(version=>version.status==="DRAFT").length}}).sort((a,b)=>a.project.name.localeCompare(b.project.name)),[boms]);return <div className="space-y-6"><PageHeader title="Manufacturing projects" description="A project-first register of definitions and production-readiness context." icon={FolderKanban}/><Card><CardContent className="p-0"><Table><TableHeader><TableRow className="bg-muted/40"><TableHead className="pl-5">Project</TableHead><TableHead className="text-right">BOMs</TableHead><TableHead className="text-right">Active</TableHead><TableHead className="text-right">Draft</TableHead><TableHead className="pr-5"/></TableRow></TableHeader><TableBody>{projects.map(row=><TableRow key={row.project.id}><TableCell className="pl-5 font-medium">{row.project.name}</TableCell><TableCell className="text-right">{row.boms}</TableCell><TableCell className="text-right"><State value="ACTIVE"/> {row.active}</TableCell><TableCell className="text-right"><State value="DRAFT"/> {row.draft}</TableCell><TableCell className="pr-5 text-right"><Button size="sm" variant="outline" onClick={()=>open(row.project.id)}>Open project</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card></div> }

function ProjectDetail({ projectId,boms,back,openBom }: { projectId:string|null;boms:Bom[];back:()=>void;openBom:(id:string)=>void }) { const rows=boms.filter(bom=>bom.projectTag?.id===projectId),project=rows[0]?.projectTag;if(!project)return <Empty title="Project was not found" action={<Button onClick={back}>Back to projects</Button>}/>;const versions=rows.flatMap(bom=>bom.versions);return <div className="space-y-6"><Button variant="ghost" className="-ml-3" onClick={back}>← Back to projects</Button><PageHeader title={project.name} description="Definitions, outputs and future manufacturing-cycle context for this project." icon={FolderKanban}/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="BOM definitions" value={rows.length} detail="Linked project definitions"/><Metric label="Active BOMs" value={versions.filter(version=>version.status==="ACTIVE").length} detail="Available for new cycles"/><Metric label="Draft BOMs" value={versions.filter(version=>version.status==="DRAFT").length} detail="Pending review"/><Metric label="Serials & deliveries" value="Not posted" detail="Appears once cycles and deliveries are live"/></div><Card><CardHeader><CardTitle className="text-base">Project BOMs</CardTitle></CardHeader><CardContent className="space-y-2">{rows.map(bom=><button className="flex w-full items-center justify-between rounded-lg border p-3 text-left hover:bg-muted/40" key={bom.id} onClick={()=>openBom(bom.id)}><span><span className="block font-medium">{bom.name}</span><span className="text-xs text-muted-foreground">{bom.item.code} · {bom.item.title}</span></span><span className="flex gap-1">{bom.versions.map(version=><State key={version.id} value={version.status}/>)}</span></button>)}</CardContent></Card></div> }

function Planning() { const [rows,setRows]=useState<Rollup[]>([]),[basis,setBasis]=useState(""),[loading,setLoading]=useState(true),[project,setProject]=useState("all"),[category,setCategory]=useState("all");useEffect(()=>{let disposed=false;void api<{rows:Rollup[];basis:string}>("/api/v1/manufacturing/planning/rollup").then(result=>{if(!disposed){setRows(result.rows);setBasis(result.basis)}}).catch(error=>{if(!disposed)toast.error(error instanceof Error?error.message:"Could not load planning roll-up")}).finally(()=>{if(!disposed)setLoading(false)});return()=>{disposed=true}},[]);const projects=useMemo(()=>[...new Map(rows.map(row=>[row.project.id,row.project])).values()],[rows]),categories=useMemo(()=>[...new Set(rows.map(row=>row.category.name))].sort(),[rows]),visible=rows.filter(row=>(project==="all"||row.project.id===project)&&(category==="all"||row.category.name===category));return <div className="space-y-6"><PageHeader title="Production planning" description="Consolidated active-BOM requirements by project and catalogue category." icon={Boxes}/><Card><CardContent className="space-y-4 pt-6"><p className="text-sm text-muted-foreground">{basis}</p><div className="grid gap-3 md:grid-cols-2"><Select value={project} onValueChange={setProject}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All projects</SelectItem>{projects.map(row=><SelectItem key={row.id} value={row.id}>{row.name}</SelectItem>)}</SelectContent></Select><Select value={category} onValueChange={setCategory}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All categories</SelectItem>{categories.map(row=><SelectItem key={row} value={row}>{row}</SelectItem>)}</SelectContent></Select></div></CardContent></Card><Card><CardContent className="p-0">{loading?<div className="flex justify-center py-16"><Loader2 className="size-5 animate-spin"/></div>:<Table><TableHeader><TableRow className="bg-muted/40"><TableHead className="pl-5">Project</TableHead><TableHead>Category</TableHead><TableHead>Component</TableHead><TableHead className="text-right">Qty / build</TableHead><TableHead>BOM definitions</TableHead></TableRow></TableHeader><TableBody>{visible.map(row=><TableRow key={`${row.project.id}:${row.category.id}:${row.item.id}`}><TableCell className="pl-5">{row.project.name}</TableCell><TableCell>{row.category.name}</TableCell><TableCell><div className="font-medium">{row.item.title}</div><div className="font-mono text-xs text-muted-foreground">{row.item.code}</div></TableCell><TableCell className="text-right tabular-nums">{row.quantityPerBuild} {row.item.unit}</TableCell><TableCell className="max-w-72 whitespace-normal text-xs text-muted-foreground">{row.bomNames.join(", ")}</TableCell></TableRow>)}{!visible.length&&<TableRow><TableCell colSpan={5} className="py-12 text-center text-muted-foreground">No active BOM material rows match this view.</TableCell></TableRow>}</TableBody></Table>}</CardContent></Card></div> }

function RefCard({ title,rows,onAdd }: { title:string;rows:Ref[];onAdd?:()=>void }) {return <Card><CardHeader className="flex flex-row items-center justify-between"><CardTitle className="flex items-center gap-2 text-base"><Wrench className="size-4"/>{title}</CardTitle>{onAdd&&<Button size="sm" variant="outline" onClick={onAdd}>Add</Button>}</CardHeader><CardContent className="space-y-2">{rows.length?rows.slice(0,5).map(row=><div className="flex items-center justify-between rounded border px-3 py-2 text-sm" key={row.id}><span><span className="font-medium">{row.code}</span> · {row.name}</span><State value={row.status}/></div>):<span className="text-sm text-muted-foreground">Nothing configured.</span>}</CardContent></Card>}
function ReferenceDialog({ kind,close,saved }: {kind:"operation"|"work-center"|"resource"|null;close:()=>void;saved:()=>void}) {const [busy,setBusy]=useState(false);const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!kind)return;const form=new FormData(event.currentTarget);setBusy(true);try{await api(`/api/v1/manufacturing/reference/${kind}`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code:String(form.get("code")||""),name:String(form.get("name")||""),...(kind==="resource"?{resourceType:"OTHER"}:{})})});toast.success("Saved");close();saved()}catch(error){toast.error(error instanceof Error?error.message:"Could not save")}finally{setBusy(false)}};return <Dialog open={Boolean(kind)} onOpenChange={open=>!open&&close()}><DialogContent><form onSubmit={submit}><DialogHeader><DialogTitle>New {kind?label(kind):"reference"}</DialogTitle></DialogHeader><div className="space-y-4 py-4"><div><Label htmlFor="code">Code</Label><Input id="code" name="code" required/></div><div><Label htmlFor="name">Name</Label><Input id="name" name="name" required/></div></div><DialogFooter><Button type="button" variant="outline" onClick={close}>Cancel</Button><Button disabled={busy}>{busy&&<Loader2 className="mr-2 size-4 animate-spin"/>}Save</Button></DialogFooter></form></DialogContent></Dialog>}
function Metric({label,value,detail}:{label:string;value:string|number;detail:string}){return <Card><CardContent className="pt-5"><div className="text-sm text-muted-foreground">{label}</div><div className="mt-1 text-2xl font-semibold tracking-tight">{value}</div><div className="mt-1 text-xs text-muted-foreground">{detail}</div></CardContent></Card>};function Action({icon,title,description,action,onClick}:{icon:React.ReactNode;title:string;description:string;action:string;onClick:()=>void}){return <Card><CardHeader><CardTitle className="flex items-center gap-2 text-base">{icon}{title}</CardTitle></CardHeader><CardContent><p className="min-h-12 text-sm text-muted-foreground">{description}</p><Button className="mt-4" variant="outline" onClick={onClick}>{action}</Button></CardContent></Card>};function State({value}:{value:string}){return <Badge variant={value==="ACTIVE"?"default":value==="DRAFT"?"secondary":"outline"}>{label(value)}</Badge>};function Loading(){return <div className="flex min-h-64 items-center justify-center"><Loader2 className="size-5 animate-spin"/></div>};function Empty({title,action}:{title:string;action?:React.ReactNode}){return <Card><CardContent className="flex min-h-64 flex-col items-center justify-center gap-4 text-center"><div className="text-sm text-muted-foreground">{title}</div>{action}</CardContent></Card>}
