"use client"

import { useCallback, useEffect, useMemo, useState } from "react"
import { GitCompareArrows } from "lucide-react"
import { toast } from "sonner"
import { PageHeader } from "@/components/shared/page-header"
import { ConfirmActionDialog } from "@/components/shared/confirm-action-dialog"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { useAuthStore } from "@/stores/auth-store"
import { useAppStore } from "@/stores/app-store"
import { itemSimilarity } from "@/lib/item-similarity"

type Item = { id:string; code:string; title:string; specification?:string|null; unit:string; discipline:string; status:string }
type Group = { id:string; name:string; description?:string|null; memberships:Array<{item:Item}> }
type Occurrence = {id:string; sourceLineKey:string; quantity:string; item:Item; bomVersion:{id:string;revision:string;status:string;bom:{id:string;name:string;projectTag?:{name:string}|null}}}
type Preview = {token:string;blockers?:string[];transfer?:string;allocations?:string;retainedStock?:string;source?:Item;target?:Item;supplierLinks?:number;demands?:Array<{id:string;name:string;move:boolean}>;purchases?:Array<{id:string;name:string;move:boolean}>;revisions:Array<{id:string;name:string;revision:string;changes?:Array<{id:string;sourceLineKey:string;from:string;to:string;quantity:string}>}>}
const selectClass = "h-10 max-w-full rounded-md border bg-background px-3 text-sm"
async function api<T>(url:string, init?:RequestInit):Promise<T>{const response=await fetch(url,init);const body=await response.json().catch(()=>({}));if(!response.ok)throw new Error(body.error||"Request failed");return body}
const post = (body:unknown,key?:string):RequestInit => ({method:"POST",headers:{"content-type":"application/json",...(key?{"idempotency-key":key}:{})},body:JSON.stringify(body)})

export function OptimizationWorkspace({manufacturing=false}:{manufacturing?:boolean}) {
  const permissions=useAuthStore(state=>state.user?.permissions||[]), navigate=useAppStore(state=>state.navigate)
  const allowed=(permission:string)=>permissions.includes(permission), canGroup=allowed("vault.catalogue.manage"), canBom=allowed("manufacturing.definitions.manage")
  const [items,setItems]=useState<Item[]>([]),[groups,setGroups]=useState<Group[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[busy,setBusy]=useState(false)
  const [tab,setTab]=useState("discover"),[query,setQuery]=useState(""),[anchor,setAnchor]=useState(""),[threshold,setThreshold]=useState(70),[specs,setSpecs]=useState(false),[selected,setSelected]=useState<string[]>([])
  const [groupId,setGroupId]=useState(""),[name,setName]=useState(""),[description,setDescription]=useState(""),[groupConfirm,setGroupConfirm]=useState<"save"|"delete"|null>(null)
  const [source,setSource]=useState(""),[target,setTarget]=useState(""),[reason,setReason]=useState(""),[options,setOptions]=useState({moveBalance:false,moveBomLines:false,moveOpenDemand:false,moveOpenPurchases:false,copySupplierLinks:false})
  const [uniformGroup,setUniformGroup]=useState(""),[replacement,setReplacement]=useState(""),[occurrences,setOccurrences]=useState<Occurrence[]>([]),[lineIds,setLineIds]=useState<string[]>([]),[occLoading,setOccLoading]=useState(false)
  const [review,setReview]=useState<{kind:"merge"|"standardize";input:unknown;preview:Preview;key:string}|null>(null),[typed,setTyped]=useState(""),[result,setResult]=useState<Array<{id:string;bomId:string;revision:string;name:string}>>([])
  const load=useCallback(async()=>{setLoading(true);setError("");try{
    const all:Item[]=[],allGroups:Group[]=[]
    // Paginate the complete catalogue, avoiding the old first-200-only matcher.
    for(let page=1;;page++){const data=await api<{items:Item[];pagination:{totalPages:number}}>(`/api/v1/items?page=${page}&pageSize=200&status=ACTIVE`);all.push(...data.items);if(page>=data.pagination.totalPages)break}
    for(let page=1;;page++){const data=await api<{groups:Group[];hasMore:boolean}>(`/api/v1/item-alternatives?page=${page}`);allGroups.push(...data.groups);if(!data.hasMore)break}
    setItems(all);setGroups(allGroups)
  }catch(e){setError((e as Error).message)}finally{setLoading(false)}},[])
  useEffect(()=>{void load()},[load])
  useEffect(()=>{setOccurrences([]);setLineIds([]);if(!uniformGroup)return;let cancelled=false;setOccLoading(true);void (async()=>{const all:Occurrence[]=[];for(let page=1;;page++){const data=await api<{occurrences:Occurrence[];hasMore:boolean}>(`/api/v1/item-optimization?groupId=${encodeURIComponent(uniformGroup)}&page=${page}`);if(cancelled)return;all.push(...data.occurrences);if(!data.hasMore)break}setOccurrences(all)})().catch(e=>{if(!cancelled)setError(e.message)}).finally(()=>{if(!cancelled)setOccLoading(false)});return()=>{cancelled=true}},[uniformGroup,groups])
  const reference=items.find(item=>item.id===anchor)
  const candidates=useMemo(()=>items.filter(item=>`${item.title} ${item.code} ${item.specification||""}`.toLowerCase().includes(query.toLowerCase())).map(item=>({item,score:reference?itemSimilarity(reference,item,specs):null})).filter(row=>!reference||row.item.id===reference.id||(row.score!>=threshold/100&&row.item.unit===reference.unit&&row.item.discipline===reference.discipline)).sort((a,b)=>(b.score||0)-(a.score||0)||a.item.title.localeCompare(b.item.title)),[items,reference,specs,threshold,query])
  const toggle=(value:string)=>setSelected(current=>current.includes(value)?current.filter(id=>id!==value):[...current,value])
  function editGroup(group?:Group){setGroupId(group?.id||"");setName(group?.name||"");setDescription(group?.description||"");setSelected(group?.memberships.map(row=>row.item.id)||[]);setTab("discover")}
  async function saveGroup(){setBusy(true);try{await api(`/api/v1/item-alternatives${groupId?`/${groupId}`:""}`,{...post({name,description,itemIds:selected}),method:groupId?"PATCH":"POST"});toast.success("Alternative group saved");setGroupConfirm(null);editGroup();await load()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function removeGroup(){setBusy(true);try{await api(`/api/v1/item-alternatives/${groupId}`,{method:"DELETE"});setGroupConfirm(null);editGroup();await load();toast.success("Group removed; component records retained")}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function preview(kind:"merge"|"standardize") {setBusy(true);setError("");const input=kind==="merge"?{sourceItemId:source,targetItemId:target,...options,reason}:{groupId:uniformGroup,targetItemId:replacement,lineIds,reason};try{const preview=await api<Preview>("/api/v1/item-optimization",post({action:`${kind}.preview`,input}));setTyped("");setReview({kind,input,preview,key:crypto.randomUUID()})}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function commit(){if(!review)return;setBusy(true);setError("");try{const output=await api<{revisions:Array<{id:string;bomId:string;revision:string;name:string}>}>("/api/v1/item-optimization",post({action:`${review.kind}.commit`,input:review.input,token:review.preview.token},review.key));setResult(output.revisions);setReview(null);setLineIds([]);setSelected([]);setSource("");setTarget("");await load();toast.success("Changes saved and audited")}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  const memberGroup=groups.find(group=>group.id===uniformGroup)
  const sourceLabel=items.find(item=>item.id===source), targetLabel=items.find(item=>item.id===target)
  const controls:Array<[keyof typeof options,string,string]>=[["moveBalance","Transfer on-hand stock by paired adjustments","vault.stock.adjust"],["moveOpenDemand","Move eligible unissued demands and their allocations","vault.demands.manage"],["moveOpenPurchases","Move eligible backlog purchase lines","vault.purchasing.manage"],["moveBomLines","Create replacement Drafts for current BOM references","manufacturing.definitions.manage"],["copySupplierLinks","Copy purchase-reference links (retain existing target URLs)","vault.catalogue.manage"]]
  return <div className="space-y-5"><PageHeader title={manufacturing?"BOM optimization":"Item simplification"} description={manufacturing?"Curate alternatives and propose consistent components in new BOM drafts.":"Review likely duplicates and merge selected current records with an audit trail."} icon={GitCompareArrows}/>
    {error&&<p role="alert" className="rounded border border-destructive p-3 text-sm text-destructive">{error}</p>}
    <div className="flex flex-wrap gap-2">{[["discover",manufacturing?"Create / edit alternatives":"Find duplicates"],["groups","Alternative groups"],[manufacturing?"uniform":"merge",manufacturing?"Make BOMs uniform":"Merge review"]].map(([key,label])=><Button key={key} variant={tab===key?"default":"outline"} onClick={()=>setTab(key)}>{label}</Button>)}<Button variant="ghost" onClick={()=>void load()} disabled={loading||busy}>Refresh</Button></div>
    {loading?<p>Loading components and groups…</p>:<>
    {tab==="discover"&&<div className="space-y-4"><div className="grid gap-3 rounded-xl border p-4 md:grid-cols-2"><label className="space-y-1 text-sm">Compare against component<select className={`${selectClass} w-full`} value={anchor} onChange={e=>setAnchor(e.target.value)}><option value="">Choose a component to find similar items</option>{items.map(item=><option key={item.id} value={item.id}>{item.title} · {item.code}</option>)}</select></label><label className="text-sm">Minimum similarity: {threshold}%<input aria-label="Matching threshold" type="range" min={0} max={100} value={threshold} onChange={e=>setThreshold(Number(e.target.value))} className="block w-full"/></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={specs} onChange={e=>setSpecs(e.target.checked)}/>Compare name and specification (both must meet threshold)</label><Input aria-label="Search components" placeholder="Search names, codes or specifications" value={query} onChange={e=>setQuery(e.target.value)}/><p className="text-xs text-muted-foreground md:col-span-2">Similarity suggests candidates only. Confirm compatibility yourself. Missing specifications do not count as a specification match.</p></div>
      <div className="rounded-xl border p-4"><p className="mb-2 text-sm">{selected.length} selected · {candidates.length} candidates</p><div className="max-h-96 overflow-auto">{candidates.map(({item,score})=><label key={item.id} className="flex gap-3 border-b p-3"><input type="checkbox" checked={selected.includes(item.id)} onChange={()=>toggle(item.id)}/><span className="flex-1"><span className="font-medium">{item.title}</span><span className="block text-xs text-muted-foreground">{item.code} · {item.unit} · {item.specification||"No specification"}</span></span>{score!==null&&<span>{Math.round(score*100)}%</span>}</label>)}</div><div className="mt-3 flex flex-wrap gap-2">{selected.map(id=><Button key={id} size="sm" variant="secondary" onClick={()=>toggle(id)}>{items.find(item=>item.id===id)?.title||groups.flatMap(g=>g.memberships).find(m=>m.item.id===id)?.item.title||id} ×</Button>)}</div>
      {!manufacturing&&<Button className="mt-3" disabled={selected.length!==2} onClick={()=>{setSource(selected[0]);setTarget(selected[1]);setTab("merge")}}>Review these two items for merging</Button>}</div>
      {canGroup&&<div className="space-y-3 rounded-xl border p-4"><h2 className="font-semibold">{groupId?"Edit alternative group":"Create alternative group"}</h2><Input aria-label="Group name" placeholder="Group name" value={name} onChange={e=>setName(e.target.value)}/><Input aria-label="Group description" placeholder="Compatibility notes" value={description} onChange={e=>setDescription(e.target.value)}/><Button disabled={busy||selected.length<2||!name.trim()} onClick={()=>setGroupConfirm("save")}>Review group membership</Button>{groupId&&<Button variant="ghost" onClick={()=>editGroup()}>Cancel editing</Button>}</div>}
    </div>}
    {tab==="groups"&&<div className="space-y-3">{!groups.length&&<p>No alternative groups yet.</p>}{groups.map(group=><section className="rounded-xl border p-4" key={group.id}><h2 className="font-semibold">{group.name}</h2><p className="text-sm text-muted-foreground">{group.description}</p><ul className="my-3 list-inside list-disc text-sm">{group.memberships.map(({item})=><li key={item.id}>{item.title} · {item.code} · {item.status}</li>)}</ul><div className="flex gap-2">{canGroup&&<><Button size="sm" variant="outline" onClick={()=>editGroup(group)}>Edit members</Button><Button size="sm" variant="ghost" onClick={()=>{setGroupId(group.id);setName(group.name);setGroupConfirm("delete")}}>Remove group</Button></>}{manufacturing&&<Button size="sm" onClick={()=>{setUniformGroup(group.id);setReplacement("");setTab("uniform")}}>Review BOM occurrences</Button>}</div></section>)}</div>}
    {tab==="merge"&&!manufacturing&&<div className="space-y-4 rounded-xl border p-4"><h2 className="font-semibold">Source and survivor</h2><div className="grid gap-3 md:grid-cols-2">{[[source,setSource,"Source to archive"],[target,setTarget,"Surviving component"]].map(([value,setter,label])=><label key={String(label)} className="text-sm">{String(label)}<select className={`${selectClass} block w-full`} value={value as string} onChange={e=>(setter as (v:string)=>void)(e.target.value)}><option value="">Choose component</option>{items.map(item=><option key={item.id} value={item.id}>{item.title} · {item.code}</option>)}</select></label>)}</div><p className="text-sm">{sourceLabel?.title||"Source"} → {targetLabel?.title||"Survivor"}. Historical issues, receipts and orders stay on their original component. Unselected stock and references remain on the archived source and are listed in the audit.</p>{controls.map(([key,label,permission])=><label className="flex gap-2 text-sm" key={key}><input type="checkbox" disabled={!allowed(permission)} checked={options[key]} onChange={e=>setOptions({...options,[key]:e.target.checked})}/>{label}{!allowed(permission)&&" (permission required)"}</label>)}<Input aria-label="Merge reason" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason for correcting this duplicate"/><Button disabled={busy||!source||!target||source===target||!reason.trim()} onClick={()=>void preview("merge")}>Preview merge impact</Button></div>}
    {tab==="uniform"&&manufacturing&&<div className="space-y-4 rounded-xl border p-4"><div className="flex flex-wrap gap-3"><select aria-label="Alternative group" className={selectClass} value={uniformGroup} onChange={e=>{setUniformGroup(e.target.value);setReplacement("")}}><option value="">Choose group</option>{groups.map(group=><option key={group.id} value={group.id}>{group.name}</option>)}</select><select aria-label="Replacement component" className={selectClass} value={replacement} onChange={e=>{setReplacement(e.target.value);setLineIds([])}}><option value="">Choose common component</option>{memberGroup?.memberships.filter(m=>m.item.status==="ACTIVE").map(({item})=><option key={item.id} value={item.id}>{item.title} · {item.code}</option>)}</select></div><p className="text-sm">Select exact occurrences to replace. Each selected source revision is copied into a new Draft with only these component references changed. Review and activate the Draft separately.</p>{occLoading?<p>Loading occurrences…</p>:<div className="max-h-96 overflow-auto"><table className="w-full text-left text-sm"><thead><tr><th>Select</th><th>Project / BOM</th><th>Revision</th><th>Line / component</th><th>Quantity</th></tr></thead><tbody>{occurrences.map(row=><tr className="border-t" key={row.id}><td className="p-2"><input aria-label={`Replace ${row.sourceLineKey} in ${row.bomVersion.bom.name}`} type="checkbox" disabled={!replacement||row.item.id===replacement} checked={lineIds.includes(row.id)} onChange={e=>setLineIds(e.target.checked?[...lineIds,row.id]:lineIds.filter(id=>id!==row.id))}/></td><td>{row.bomVersion.bom.projectTag?.name||"Shared"} / {row.bomVersion.bom.name}</td><td>{row.bomVersion.revision} · {row.bomVersion.status}</td><td>{row.sourceLineKey} · {row.item.title}</td><td>{row.quantity} {row.item.unit}</td></tr>)}</tbody></table>{uniformGroup&&!occurrences.length&&<p>No current BOM occurrences for this group.</p>}</div>}<Input aria-label="BOM optimization reason" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Reason for standardization"/><Button disabled={!canBom||busy||!replacement||!lineIds.length||!reason.trim()} onClick={()=>void preview("standardize")}>Preview {lineIds.length} replacements</Button></div>}
    </>}
    {!!result.length&&<div className="rounded-xl border p-4"><h2 className="font-semibold">Created Draft revisions</h2>{result.map(row=><Button key={row.id} variant="link" onClick={()=>navigate("manufacturing-bom-detail",row.bomId)}>{row.name} · {row.revision}</Button>)}</div>}
    <ConfirmActionDialog open={!!groupConfirm} onOpenChange={open=>{if(!open&&!busy)setGroupConfirm(null)}} title={groupConfirm==="delete"?"Remove alternative group?":"Save alternative group?"} description={groupConfirm==="delete"?`Remove ${name} and its memberships. Items and BOMs are retained. This action is audited.`:`Save ${name} with ${selected.length} explicitly selected members. Membership changes affect alternative indicators and future optimization reviews.`} confirmLabel={groupConfirm==="delete"?"Remove group":"Save group"} busy={busy} destructive={groupConfirm==="delete"} onConfirm={groupConfirm==="delete"?removeGroup:saveGroup}>{error&&<p role="alert">{error}</p>}<div className="max-h-52 overflow-auto">{groupConfirm==="save"&&selected.map(id=><p key={id}>{items.find(item=>item.id===id)?.title||id}</p>)}</div></ConfirmActionDialog>
    <ConfirmActionDialog open={!!review} onOpenChange={open=>{if(!open&&!busy)setReview(null)}} title={review?.kind==="merge"?"Confirm component merge":"Create proposed BOM drafts?"} description={review?.kind==="merge"?"The source will be archived. The selected current records will move to the survivor in one audited transaction.":"New Draft revisions will be created for the reviewed replacements. Existing versions and production runs remain unchanged."} confirmLabel={review?.kind==="merge"?"Merge and archive source":"Create Draft revisions"} destructive={review?.kind==="merge"} busy={busy} disabled={!!review?.preview.blockers?.length||(review?.kind==="merge"&&typed!==review.preview.source?.code)} onConfirm={commit}><div className="max-h-[55vh] space-y-3 overflow-auto">{error&&<p role="alert" className="text-destructive">{error}</p>}{review?.preview.blockers?.map(message=><p className="text-destructive" key={message}>{message}</p>)}{review?.kind==="merge"&&<><p>{review.preview.source?.title} ({review.preview.source?.code}) → {review.preview.target?.title} ({review.preview.target?.code})</p><p>Transfer stock: {review.preview.transfer}; transfer allocations: {review.preview.allocations}; stock retained at source: {review.preview.retainedStock}; supplier links to consider copying: {review.preview.supplierLinks}.</p>{[...(review.preview.demands||[]),...(review.preview.purchases||[])].map(row=><p key={row.id}>{row.name}: {row.move?"move to survivor":"retain on source"}</p>)}<label>Type {review.preview.source?.code} to confirm<Input aria-label="Confirm source code" value={typed} onChange={e=>setTyped(e.target.value)}/></label></>}{review?.preview.revisions.map(row=><div className="border-t pt-2" key={row.id}><strong>{row.name}</strong> · {row.revision} → new Draft{row.changes?.map(change=><p key={change.id}>{change.sourceLineKey}: {change.from} → {change.to} · {change.quantity}</p>)}</div>)}</div></ConfirmActionDialog>
  </div>
}
