import type { PlanningResult, PlanningScenario, PlanningSnapshot } from "@/lib/planning-types"

export function printPlanningReport(snapshot:PlanningSnapshot,scenario:PlanningScenario,result:PlanningResult,type:string){
  const popup=window.open("","_blank")
  if(!popup)throw new Error("Allow the report preview window, then try again.")
  const escape=(value:string)=>value.replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")
  const text=(value:unknown)=>escape(String(value??""))
  popup.document.write(`<!doctype html><html><head><title>${text(scenario.name)} — ${text(type)}</title><style>body{font:12px system-ui;margin:28px;color:#171717}h1{font-size:22px}table{width:100%;border-collapse:collapse;margin-top:20px}td,th{padding:8px;border-bottom:1px solid #ddd;text-align:left}thead{display:table-header-group}tr{break-inside:avoid}small{color:#555}@page{size:A4 landscape;margin:15mm}@media print{button{display:none}}</style></head><body><button onclick="window.print()">Print / Save as PDF</button><h1>${text(scenario.name)} — ${text(type)}</h1><p>Evidence: ${text(snapshot.timestamp)} · ${result.missingPrices} missing prices · ${Object.keys(scenario.edits).length} BOMs contain scenario changes</p><p>Scope: ${text(scenario.categoryIds?.map(id=>snapshot.categories.find(row=>row.id===id)?.name||id).join(", ")||"All categories")}</p>${scenario.selections.map(selection=>{const version=snapshot.versions.find(row=>row.id===selection.versionId);return `<div>${text(version?.project.name)} / ${text(version?.name)} / ${text(version?.revision)}: ${text(selection.quantity)} builds</div>`}).join("")}<p>Historical material prices; currencies are separate. Stock coverage is hypothetical and does not reserve inventory.</p><table><thead><tr><th>Component</th><th>Category</th><th>Required</th><th>After assembly stock</th><th>From store</th><th>To buy</th><th>Unit price</th><th>${type==="purchase"?"Purchase cost":"Material cost"}</th></tr></thead><tbody>${result.materials.map(row=>`<tr><td>${text(row.item.title)}<br><small>${text(row.item.code)}</small></td><td>${text(row.category)}</td><td>${text(row.required)} ${text(row.item.unit)}</td><td>${text(row.afterAssembly)}</td><td>${text(row.stockUsed)}</td><td>${text(row.toBuy)}</td><td>${row.item.price?`${text(row.item.price.amount)} ${text(row.item.price.currency)}`:"Missing"}</td><td>${text((type==="purchase"?row.purchaseCost:row.cost)??"Unknown")} ${text(row.item.price?.currency)}</td></tr>`).join("")}</tbody></table><h2>${result.missingPrices?"Known costs — partial":"Estimated costs"}</h2>${result.totals.map(total=>`<p>${text(total.currency)}: ${text(type==="purchase"?total.purchase:total.material)}</p>`).join("")}<h2>Attribution and evidence</h2>${result.materials.map(row=>`<p><strong>${text(row.item.title)}</strong><br>${row.contributions.map(entry=>`${text(entry.project)} / ${text(entry.bom)} / ${text(entry.path)}: ${text(entry.quantity)}`).join("<br>")}<br><small>Price: ${text(row.item.price?.source||"Missing")} ${text(row.item.price?.effectiveAt)}</small></p>`).join("")}</body></html>`)
  popup.document.close()
}

export async function downloadPlanningWorkbook(snapshot:PlanningSnapshot,scenario:PlanningScenario,result:PlanningResult,type:string){
  const ExcelJS=await import("exceljs")
  const workbook=new ExcelJS.Workbook()
  workbook.creator="Production planning"
  const basis=workbook.addWorksheet("Scenario basis")
  basis.addRows([["Scenario",scenario.name],["Report",type],["Evidence timestamp",snapshot.timestamp],["Generated",new Date().toISOString()],["Category scope",scenario.categoryIds?.map(id=>snapshot.categories.find(category=>category.id===id)?.name||id).join(", ")||"All categories"],["Sandbox changes",Object.keys(scenario.edits).length?"Includes uncommitted scenario BOM changes":"None"],["Missing prices",result.missingPrices],["Cost scope","Historical material prices; excludes labour, freight, duties and overhead"],["Stock basis","Free physical stock used once; hypothetical coverage, not a reservation"],[],["Project","BOM","Revision","Build quantity"]])
  for(const selection of scenario.selections){const version=snapshot.versions.find(version=>version.id===selection.versionId);basis.addRow([version?.project.name,version?.name,version?.revision,selection.quantity])}
  for(const warning of result.warnings)basis.addRow(["Attention",warning])
  const sheet=workbook.addWorksheet(type==="purchase"?"Purchase list":"Consolidated materials")
  sheet.addRow(["Code","Component","Category","Unit","Gross required","After assembly coverage","Store use","Additional to buy","Unit price","Currency","Material cost","Purchase cost","Price date","Price source"])
  for(const row of result.materials)sheet.addRow([row.item.code,row.item.title,row.category,row.item.unit,Number(row.required),Number(row.afterAssembly),Number(row.stockUsed),Number(row.toBuy),row.item.price?Number(row.item.price.amount):"Missing price",row.item.price?.currency||"",row.cost===null?"Unknown":Number(row.cost),row.purchaseCost===null?"Unknown":Number(row.purchaseCost),row.item.price?.effectiveAt||"",row.item.price?.source||""])
  const attribution=workbook.addWorksheet("Attribution");attribution.addRow(["Component","Project","BOM","Revision","Path","Gross quantity","Unit"])
  for(const row of result.materials)for(const contribution of row.contributions)attribution.addRow([row.item.title,contribution.project,contribution.bom,contribution.revision,contribution.path,Number(contribution.quantity),row.item.unit])
  const totals=workbook.addWorksheet("Cost totals");totals.addRow(["Currency",result.missingPrices?"Known material cost (partial)":"Material cost","Known purchase cost"]);result.totals.forEach(total=>totals.addRow([total.currency,Number(total.material),Number(total.purchase)]))
  const changes=workbook.addWorksheet("BOM changes");changes.addRow(["BOM","Source key","Original","Scenario"])
  for(const [versionId,lines] of Object.entries(scenario.edits)){const version=snapshot.versions.find(version=>version.id===versionId);for(const key of new Set([...lines,...(version?.lines||[])].map(line=>line.sourceLineKey))){const before=version?.lines.find(line=>line.sourceLineKey===key),after=lines.find(line=>line.sourceLineKey===key);if(JSON.stringify(before)!==JSON.stringify(after))changes.addRow([version?.name,key,JSON.stringify(before)||"Added",JSON.stringify(after)||"Removed"])}}
  workbook.eachSheet(worksheet=>{worksheet.views=[{state:"frozen",ySplit:1}];worksheet.getRow(1).font={bold:true};worksheet.columns.forEach(column=>{column.width=24});worksheet.eachRow(row=>row.eachCell(cell=>{if(typeof cell.value==="string"&&/^[=+@-]/.test(cell.value))cell.value="'"+cell.value}))})
  const bytes=await workbook.xlsx.writeBuffer(),url=URL.createObjectURL(new Blob([bytes],{type:"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"})),link=document.createElement("a")
  link.href=url;link.download=`${scenario.name.replace(/[^a-z0-9_-]/gi,"_")}_${type}_${new Date().toISOString().slice(0,10)}.xlsx`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000)
}
