-- Manufacturing Phase 2: planning facts and immutable released-order snapshots.
CREATE TYPE "ProductionPlanStatus" AS ENUM ('DRAFT', 'ACTIVE', 'CLOSED', 'CANCELLED');
CREATE TYPE "ProductionOrderStatus" AS ENUM ('DRAFT', 'PLANNED', 'RELEASED', 'IN_PROGRESS', 'COMPLETED', 'CLOSED', 'CANCELLED');

CREATE TABLE "production_plans" ("id" TEXT NOT NULL, "projectTagId" TEXT NOT NULL, "name" TEXT NOT NULL, "status" "ProductionPlanStatus" NOT NULL DEFAULT 'DRAFT', "notes" TEXT, "createdById" TEXT NOT NULL, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "production_plans_pkey" PRIMARY KEY ("id"), CONSTRAINT "production_plans_projectTagId_fkey" FOREIGN KEY ("projectTagId") REFERENCES "project_tags"("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "production_plans_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE INDEX "production_plans_projectTagId_status_idx" ON "production_plans"("projectTagId", "status");

CREATE TABLE "production_plan_lines" ("id" TEXT NOT NULL, "productionPlanId" TEXT NOT NULL, "itemId" TEXT NOT NULL, "targetQty" DECIMAL(18,6) NOT NULL, "requiredDate" TIMESTAMP(3), "priority" INTEGER, "notes" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "production_plan_lines_pkey" PRIMARY KEY ("id"), CONSTRAINT "production_plan_lines_targetQty_check" CHECK ("targetQty" > 0), CONSTRAINT "production_plan_lines_productionPlanId_fkey" FOREIGN KEY ("productionPlanId") REFERENCES "production_plans"("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "production_plan_lines_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "items"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE UNIQUE INDEX "production_plan_lines_productionPlanId_itemId_key" ON "production_plan_lines"("productionPlanId", "itemId");

CREATE TABLE "production_orders" ("id" TEXT NOT NULL, "orderNumber" TEXT NOT NULL, "projectTagId" TEXT NOT NULL, "productionPlanLineId" TEXT, "itemId" TEXT NOT NULL, "plannedQty" DECIMAL(18,6) NOT NULL, "bomVersionId" TEXT, "routeVersionId" TEXT, "status" "ProductionOrderStatus" NOT NULL DEFAULT 'DRAFT', "plannedStart" TIMESTAMP(3), "plannedEnd" TIMESTAMP(3), "actualStart" TIMESTAMP(3), "completedAt" TIMESTAMP(3), "createdById" TEXT NOT NULL, "releasedAt" TIMESTAMP(3), "releasedById" TEXT, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "production_orders_pkey" PRIMARY KEY ("id"), CONSTRAINT "production_orders_plannedQty_check" CHECK ("plannedQty" > 0), CONSTRAINT "production_orders_projectTagId_fkey" FOREIGN KEY ("projectTagId") REFERENCES "project_tags"("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "production_orders_productionPlanLineId_fkey" FOREIGN KEY ("productionPlanLineId") REFERENCES "production_plan_lines"("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "production_orders_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "items"("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "production_orders_bomVersionId_fkey" FOREIGN KEY ("bomVersionId") REFERENCES "bom_versions"("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "production_orders_routeVersionId_fkey" FOREIGN KEY ("routeVersionId") REFERENCES "route_versions"("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "production_orders_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "production_orders_releasedById_fkey" FOREIGN KEY ("releasedById") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE UNIQUE INDEX "production_orders_orderNumber_key" ON "production_orders"("orderNumber"); CREATE INDEX "production_orders_projectTagId_status_idx" ON "production_orders"("projectTagId", "status"); CREATE INDEX "production_orders_itemId_status_idx" ON "production_orders"("itemId", "status"); CREATE INDEX "production_orders_productionPlanLineId_idx" ON "production_orders"("productionPlanLineId");

CREATE TABLE "production_order_components" ("id" TEXT NOT NULL, "productionOrderId" TEXT NOT NULL, "sourceBomLineId" TEXT, "itemId" TEXT NOT NULL, "requiredQty" DECIMAL(18,6) NOT NULL, "consumptionSequence" INTEGER, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "production_order_components_pkey" PRIMARY KEY ("id"), CONSTRAINT "production_order_components_requiredQty_check" CHECK ("requiredQty" > 0), CONSTRAINT "production_order_components_productionOrderId_fkey" FOREIGN KEY ("productionOrderId") REFERENCES "production_orders"("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "production_order_components_itemId_fkey" FOREIGN KEY ("itemId") REFERENCES "items"("id") ON DELETE RESTRICT ON UPDATE CASCADE);
CREATE UNIQUE INDEX "production_order_components_order_source_key" ON "production_order_components"("productionOrderId", "sourceBomLineId"); CREATE INDEX "production_order_components_itemId_idx" ON "production_order_components"("itemId");

CREATE TABLE "production_operations" ("id" TEXT NOT NULL, "productionOrderId" TEXT NOT NULL, "sourceRouteStepId" TEXT, "operationId" TEXT NOT NULL, "sequence" INTEGER NOT NULL, "name" TEXT NOT NULL, "workCenterId" TEXT, "executionMode" "RouteExecutionMode" NOT NULL, "isSerializationPoint" BOOLEAN NOT NULL DEFAULT false, "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, CONSTRAINT "production_operations_pkey" PRIMARY KEY ("id"), CONSTRAINT "production_operations_productionOrderId_fkey" FOREIGN KEY ("productionOrderId") REFERENCES "production_orders"("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "production_operations_operationId_fkey" FOREIGN KEY ("operationId") REFERENCES "manufacturing_operations"("id") ON DELETE RESTRICT ON UPDATE CASCADE, CONSTRAINT "production_operations_workCenterId_fkey" FOREIGN KEY ("workCenterId") REFERENCES "work_centers"("id") ON DELETE SET NULL ON UPDATE CASCADE);
CREATE UNIQUE INDEX "production_operations_order_sequence_key" ON "production_operations"("productionOrderId", "sequence"); CREATE INDEX "production_operations_operationId_idx" ON "production_operations"("operationId");
