import test from "node:test"
import assert from "node:assert/strict"
import { PrismaClient } from "@prisma/client"
import { CargoError, cargoReport, cargoShipmentDetail, executeCargoAction } from "../../src/lib/cargo-service"

const enabled = Boolean(process.env.DATABASE_URL)
const prisma = new PrismaClient()

test("Cargo shipment identity, journey locking, costs and cross-shipment links", { skip: !enabled }, async () => {
  const suffix = Date.now().toString()
  const user = await prisma.user.create({ data: { email: `cargo-${suffix}@test.local`, name: "Cargo Test", password: "not-used" } })
  const actor = { id: user.id, name: user.name }
  const first = await executeCargoAction("package.create", { route: "DIRECT", weight: 2.5, length: 10, width: 20, height: 30 }, actor)
  assert.ok(first && "shipmentId" in first)
  const firstShipmentId = String(first.shipmentId)
  const second = await executeCargoAction("shipment.create", { route: "DIRECT" }, actor)
  assert.ok(second && "id" in second)
  const secondShipmentId = String(second.id)
  const named = await executeCargoAction("shipment.create", { shipmentNo: `AL-2026-${suffix}`, route: "DIRECT" }, actor)
  assert.equal((await prisma.cargoShipment.findUniqueOrThrow({ where: { id: String(named.id) } })).shipmentNo, `AL-2026-${suffix}`)
  await assert.rejects(executeCargoAction("shipment.create", { shipmentNo: `al-2026-${suffix}`, route: "DIRECT" }, actor), (error: unknown) => error instanceof CargoError && error.code === "DUPLICATE_IDENTIFIER")
  await executeCargoAction("shipment.archive", { id: String(named.id), archived: true }, actor)
  assert.equal((await prisma.cargoShipment.findUniqueOrThrow({ where: { id: String(named.id) } })).status, "ARCHIVED")
  const retryKey = `cargo-create-${suffix}`
  const retryable = await executeCargoAction("shipment.create", { route: "DIRECT" }, actor, retryKey)
  const repeated = await executeCargoAction("shipment.create", { route: "DIRECT" }, actor, retryKey)
  assert.equal(repeated.id, retryable.id)
  await assert.rejects(executeCargoAction("shipment.create", { route: "FORWARDED" }, actor, retryKey), (error: unknown) => error instanceof CargoError && error.code === "IDEMPOTENCY_KEY_CONFLICT")
  assert.equal(await prisma.cargoRequestKey.count({ where: { actorId: user.id, key: retryKey } }), 1)
  const shared = await executeCargoAction("package.create", { shipmentId: firstShipmentId }, actor)
  assert.ok(shared && "id" in shared)
  const item = await executeCargoAction("item.save", { packageId: String(shared.id), description: "Part", quantity: 4 }, actor)
  assert.ok(item && "id" in item)

  const invoice = await executeCargoAction("invoice.save", { shipmentId: firstShipmentId, packageId: String(shared.id), currency: "USD", totalAmount: 120, invoiceNo: "I-1" }, actor)
  assert.ok(invoice && "id" in invoice)
  const charge = await executeCargoAction("charge.save", { shipmentId: firstShipmentId, invoiceId: String(invoice.id), category: "INTERNATIONAL_FREIGHT", amount: 100, currency: "USD", pkrEquivalent: 28000, pkrNote: "Bank settlement" }, actor)
  assert.ok(charge && "id" in charge)
  const detail = await cargoShipmentDetail(firstShipmentId, ["cargo.view", "cargo.costs.view", "cargo.documents.view"])
  assert.equal(detail?.packages.length, 2)
  assert.equal(detail?.charges?.[0].amount.toString(), "100")
  assert.equal(detail?.invoices?.[0].totalAmount?.toString(), "120")
  assert.equal((await cargoShipmentDetail(firstShipmentId, ["cargo.view"]))?.charges, undefined)
  const report = await cargoReport(true)
  assert.ok(report.charges.some(row => row.category === "INTERNATIONAL_FREIGHT" && row.currency === "USD" && Number(row.amount) >= 100))
  assert.deepEqual((await cargoReport(false)).charges, [])

  await assert.rejects(executeCargoAction("invoice.save", { shipmentId: secondShipmentId, packageId: String(shared.id), currency: "USD", totalAmount: 1 }, actor))
  await assert.rejects(executeCargoAction("package.reassign", { id: String(shared.id), shipmentId: secondShipmentId }, actor), (error: unknown) => error instanceof CargoError && error.code === "PACKAGE_HAS_HISTORY")
  await executeCargoAction("milestone.post", { shipmentId: secondShipmentId, stage: "IN_INTERNATIONAL_TRANSIT", occurredAt: new Date(Date.now() + 1000).toISOString() }, actor)
  await assert.rejects(executeCargoAction("package.reassign", { id: String(first.id), shipmentId: secondShipmentId }, actor), (error: unknown) => error instanceof CargoError && error.code === "JOURNEY_LOCKED")
  await assert.rejects(executeCargoAction("milestone.post", { shipmentId: secondShipmentId, stage: "CUSTOMS_CLEARED", occurredAt: new Date(Date.now() + 2000).toISOString() }, actor), (error: unknown) => error instanceof CargoError && error.code === "INVALID_STAGE")
  assert.equal(await prisma.cargoMilestone.count({ where: { shipmentId: secondShipmentId } }), 2)
  assert.ok(await prisma.auditLog.count({ where: { userId: user.id, action: { startsWith: "CARGO_" } } }) >= 6)

  const disposable = await executeCargoAction("shipment.create", { shipmentNo: `DELETE-${suffix}`, route: "DIRECT" }, actor)
  await executeCargoAction("shipment.delete", { id: String(disposable.id) }, actor)
  assert.equal(await prisma.cargoShipment.findUnique({ where: { id: String(disposable.id) } }), null)
  await assert.rejects(executeCargoAction("shipment.delete", { id: firstShipmentId }, actor), (error: unknown) => error instanceof CargoError && error.code === "SHIPMENT_HAS_HISTORY")
})

test("forwarded routes require correct warehouse and advance through source", { skip: !enabled }, async () => {
  const suffix = Date.now().toString()
  const user = await prisma.user.create({ data: { email: `cargo-forward-${suffix}@test.local`, name: "Cargo Test", password: "not-used" } })
  const actor = { id: user.id, name: user.name }
  const forwarder = await executeCargoAction("reference.create", { kind: "forwarder", name: `Forwarder ${suffix}` }, actor)
  const other = await executeCargoAction("reference.create", { kind: "forwarder", name: `Other ${suffix}` }, actor)
  assert.ok(forwarder && "id" in forwarder && other && "id" in other)
  const warehouse = await executeCargoAction("reference.create", { kind: "warehouse", name: `Warehouse ${suffix}`, forwarderId: String(forwarder.id) }, actor)
  assert.ok(warehouse && "id" in warehouse)
  await assert.rejects(executeCargoAction("shipment.create", { route: "FORWARDED", forwarderId: String(other.id), sourceWarehouseId: String(warehouse.id) }, actor))
  const shipment = await executeCargoAction("shipment.create", { route: "FORWARDED", forwarderId: String(forwarder.id), sourceWarehouseId: String(warehouse.id) }, actor)
  assert.ok(shipment && "id" in shipment)
  const autoSelected = await executeCargoAction("shipment.create", { route: "FORWARDED", forwarderId: String(forwarder.id) }, actor)
  assert.ok(autoSelected && "sourceWarehouseId" in autoSelected)
  assert.equal(autoSelected.sourceWarehouseId, warehouse.id)
  const movable = await executeCargoAction("package.create", { shipmentId: String(shipment.id) }, actor)
  assert.ok(movable && "id" in movable)
  await executeCargoAction("package.reassign", { id: String(movable.id), shipmentId: String(autoSelected.id) }, actor)
  assert.equal((await prisma.cargoPackage.findUniqueOrThrow({ where: { id: String(movable.id) } })).shipmentId, autoSelected.id)
  await assert.rejects(executeCargoAction("milestone.post", { shipmentId: String(shipment.id), stage: "IN_INTERNATIONAL_TRANSIT", occurredAt: new Date(Date.now() + 1000).toISOString() }, actor))
  await executeCargoAction("milestone.post", { shipmentId: String(shipment.id), stage: "TO_SOURCE_WAREHOUSE", occurredAt: new Date(Date.now() + 1000).toISOString() }, actor)
  assert.equal((await prisma.cargoMilestone.findMany({ where: { shipmentId: String(shipment.id) }, orderBy: { sequence: "asc" } })).at(-1)?.stage, "TO_SOURCE_WAREHOUSE")
  await executeCargoAction("tracking.save", { shipmentId: String(autoSelected.id), kind: "SOURCE_INLAND", trackingNumber: "CN-1" }, actor)
  await assert.rejects(executeCargoAction("package.reassign", { id: String(movable.id), shipmentId: String(shipment.id) }, actor), (error: unknown) => error instanceof CargoError && error.code === "JOURNEY_LOCKED")
})

test("matching tracked shipments merge without losing package-linked history", { skip: !enabled }, async () => {
  const suffix = Date.now().toString()
  const user = await prisma.user.create({ data: { email: `cargo-merge-${suffix}@test.local`, name: "Cargo Merge Test", password: "not-used" } })
  const actor = { id: user.id, name: user.name }
  const firstPackage = await executeCargoAction("package.create", { shipmentNo: `MERGE-A-${suffix}`, packageNo: `MERGE-PA-${suffix}`, route: "DIRECT" }, actor)
  const secondPackage = await executeCargoAction("package.create", { shipmentNo: `MERGE-B-${suffix}`, packageNo: `MERGE-PB-${suffix}`, route: "DIRECT" }, actor)
  assert.ok(firstPackage && "id" in firstPackage && "shipmentId" in firstPackage)
  assert.ok(secondPackage && "id" in secondPackage && "shipmentId" in secondPackage)
  const targetShipmentId = String(firstPackage.shipmentId), sourceShipmentId = String(secondPackage.shipmentId), sourcePackageId = String(secondPackage.id)
  await executeCargoAction("tracking.save", { shipmentId: targetShipmentId, kind: "INTERNATIONAL", trackingNumber: "SHARED-TRACKING" }, actor)
  const sourceTracking = await executeCargoAction("tracking.save", { shipmentId: sourceShipmentId, kind: "INTERNATIONAL", trackingNumber: " shared-tracking " }, actor)
  assert.ok(sourceTracking && "id" in sourceTracking)
  const invoice = await executeCargoAction("invoice.save", { shipmentId: sourceShipmentId, packageId: sourcePackageId, trackingLegId: String(sourceTracking.id), currency: "USD", totalAmount: "25" }, actor)
  assert.ok(invoice && "id" in invoice)
  const charge = await executeCargoAction("charge.save", { shipmentId: sourceShipmentId, packageId: sourcePackageId, trackingLegId: String(sourceTracking.id), invoiceId: String(invoice.id), category: "INTERNATIONAL_FREIGHT", amount: "25", currency: "USD" }, actor)
  assert.ok(charge && "id" in charge)
  const file = await prisma.cargoFile.create({ data: { shipmentId: sourceShipmentId, packageId: sourcePackageId, invoiceId: String(invoice.id), kind: "CARTON_PHOTO", fileName: "carton.png", contentType: "image/png", sizeBytes: 3, sha256: "a".repeat(64), data: Buffer.from("png"), uploadedById: user.id } })
  const legacyEvent = await prisma.cargoLegacyEvent.create({ data: { id: `merge-event-${suffix}`, shipmentId: sourceShipmentId, packageId: sourcePackageId, rawStatus: "RECEIVED", occurredAt: new Date() } })
  const key = `cargo-merge-${suffix}`
  const result = await executeCargoAction("shipment.merge", { targetShipmentId, sourceShipmentIds: [sourceShipmentId], trackingNumber: "SHARED-TRACKING" }, actor, key)
  assert.ok(result && "packageCount" in result)
  assert.equal(result.id, targetShipmentId)
  assert.equal(result.packageCount, 2)
  const repeated = await executeCargoAction("shipment.merge", { targetShipmentId, sourceShipmentIds: [sourceShipmentId], trackingNumber: "SHARED-TRACKING" }, actor, key)
  assert.ok(repeated && "packageCount" in repeated)
  assert.equal(repeated.packageCount, 2)
  assert.equal(await prisma.cargoShipment.findUnique({ where: { id: sourceShipmentId } }), null)
  assert.equal((await prisma.cargoPackage.findUniqueOrThrow({ where: { id: sourcePackageId } })).shipmentId, targetShipmentId)
  assert.equal((await prisma.cargoInvoice.findUniqueOrThrow({ where: { id: String(invoice.id) } })).shipmentId, targetShipmentId)
  assert.equal((await prisma.cargoCharge.findUniqueOrThrow({ where: { id: String(charge.id) } })).shipmentId, targetShipmentId)
  assert.equal((await prisma.cargoFile.findUniqueOrThrow({ where: { id: file.id } })).shipmentId, targetShipmentId)
  assert.equal((await prisma.cargoLegacyEvent.findUniqueOrThrow({ where: { id: legacyEvent.id } })).shipmentId, targetShipmentId)
  assert.equal(await prisma.cargoTrackingLeg.count({ where: { shipmentId: targetShipmentId } }), 1)
  assert.equal(await prisma.auditLog.count({ where: { action: "CARGO_SHIPMENT_MERGE", entityId: targetShipmentId } }), 1)
})
