import assert from "node:assert/strict"
import test from "node:test"
import { calculatePlanning } from "../../src/lib/planning-calculator"
import type { PlanningSnapshot,PlanningScenario,PlanningLine } from "../../src/lib/planning-types"
const line=(key:string,itemId:string,quantity:string,parent:string|null=null):PlanningLine=>({sourceLineKey:key,parentSourceLineKey:parent,itemId,quantity,unit:null,notes:null,sortOrder:0,scrapAllowance:null,consumptionRouteStepId:null,applicability:[]})
function fixture():{snapshot:PlanningSnapshot;scenario:PlanningScenario}{return {snapshot:{timestamp:"2026-09-24T00:00:00Z",categories:[{id:"cat",name:"Electronics",parentId:null,discipline:"ELECTRONICS"}],items:[{id:"a",title:"Assembly",code:"A",unit:"pcs",categoryId:null,specification:null,manufacturerPartNumber:null,supplyMode:null,onHand:"4",reserved:"0",price:null},{id:"b",title:"Material",code:"B",unit:"pcs",categoryId:"cat",specification:null,manufacturerPartNumber:null,supplyMode:null,onHand:"7",reserved:"2",price:{id:"price",amount:"0.1",currency:"USD",effectiveAt:"2026-09-23T00:00:00Z",source:"MANUAL"}}],versions:[{id:"v1",bomId:"bom",name:"BOM",revision:"1",status:"ACTIVE",project:{id:"p",name:"Project"},output:"Output",lines:[line("a","a","1"),line("b","b","2","a")]}]},scenario:{name:"Test",categoryIds:null,edits:{},selections:[{versionId:"v1",quantity:"10"}]}}}
test("assembly coverage precedes child stock and respects allocations",()=>{const {snapshot,scenario}=fixture();const result=calculatePlanning(snapshot,scenario);assert.equal(result.materials[0].required,"20");assert.equal(result.materials[0].afterAssembly,"12");assert.equal(result.materials[0].stockUsed,"5");assert.equal(result.materials[0].toBuy,"7");assert.equal(result.materials[0].cost,"2");assert.equal(result.materials[0].purchaseCost,"0.7")})
test("category scope does not prune the parent assembly",()=>{const {snapshot,scenario}=fixture();scenario.categoryIds=["cat"];assert.equal(calculatePlanning(snapshot,scenario).materials[0].toBuy,"7")})
test("stock shared once between projects",()=>{const {snapshot,scenario}=fixture();snapshot.versions.push({...snapshot.versions[0],id:"v2",project:{id:"q",name:"Other"}});scenario.selections.push({versionId:"v2",quantity:"10"});const row=calculatePlanning(snapshot,scenario).materials[0];assert.equal(row.required,"40");assert.equal(row.toBuy,"27");assert.equal(row.contributions.length,2)})
test("missing prices are not zero",()=>{const {snapshot,scenario}=fixture();snapshot.items[1].price=null;const result=calculatePlanning(snapshot,scenario);assert.equal(result.missingPrices,1);assert.equal(result.materials[0].cost,null);assert.deepEqual(result.totals,[])})
test("invalid hierarchy and decimal inputs rejected",()=>{const {snapshot,scenario}=fixture();scenario.selections[0].quantity="0";assert.throws(()=>calculatePlanning(snapshot,scenario),/positive/);scenario.selections[0].quantity="1";snapshot.versions[0].lines[0].parentSourceLineKey="b";assert.throws(()=>calculatePlanning(snapshot,scenario),/ancestor/)})
test("direct and assembly occurrences use the same stock pool",()=>{const {snapshot,scenario}=fixture();snapshot.versions[0].lines.push(line("direct","a","1"));const result=calculatePlanning(snapshot,scenario);assert.equal(result.materials.find(row=>row.item.id==="a")?.toBuy,"10");assert.equal(result.materials.find(row=>row.item.id==="b")?.toBuy,"7")})
test("zero recorded price is evidence, not missing",()=>{const {snapshot,scenario}=fixture();snapshot.items[1].price!.amount="0";const result=calculatePlanning(snapshot,scenario);assert.equal(result.missingPrices,0);assert.equal(result.materials[0].cost,"0")})
test("scenario edits leave the baseline unchanged",()=>{const {snapshot,scenario}=fixture();scenario.edits.v1=snapshot.versions[0].lines.map(row=>row.itemId==="b"?{...row,quantity:"0.25"}:row);const result=calculatePlanning(snapshot,scenario);assert.equal(result.materials[0].required,"2.5");assert.equal(snapshot.versions[0].lines[1].quantity,"2")})
