"use client"

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react"
import { toast } from "sonner"
import {
  ArrowRight, Building2, Check, CheckCircle2, ChevronRight, CircleDollarSign, ClipboardList,
  Download, FileText, Link2, Loader2, PackageCheck, Paperclip, Plus, RefreshCw, Search,
  Ship, ShoppingCart, Trash2, Upload, UserRound, Warehouse,
} from "lucide-react"
import { ItemPicker, type CatalogueCategory, type CatalogueItem } from "@/components/shared/item-picker"
import { PageHeader } from "@/components/shared/page-header"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Progress } from "@/components/ui/progress"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Separator } from "@/components/ui/separator"
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Textarea } from "@/components/ui/textarea"
import { useAuthStore } from "@/stores/auth-store"
import { cn } from "@/lib/utils"

type Ref = { id: string; name: string }
type Item = CatalogueItem & { status?: string; balance?: { onHand: string; reserved: string } }
type ReferenceData = { itemCategories: CatalogueCategory[]; departments: Ref[]; projects: Ref[]; vendors: Ref[] }
type Quantities = {
  required: string; reserved: string; allocated: string; returned?: string; cancelled?: string; remaining: string
  backlog: string; pendingApproval: string; ordered: string; shipped: string
  physicalDeficit: string; unprocuredDeficit: string; fulfilmentFacet: string; stockFacet: string
}
type PurchaseLink = {
  id: string; quantity: string
  purchaseRequestLine: { id: string; quantity: string; receiptLines?: Array<{ quantity: string }>; purchaseRequest: PurchaseHeader }
}
type DemandLine = {
  id: string; title: string; description?: string | null; unit: string; procurementType?: string | null
  item?: Item | null; projectTag?: Ref | null; suggestedCategory?: CatalogueCategory | null; vendor?: Ref | null
  quantities: Quantities
  allocationLines: Array<{ id: string; quantity: string; returnLines: Array<{ quantity: string }> }>
  purchaseLinks: PurchaseLink[]
}
type DemandHeader = {
  id: string; demandNo: string; state: string; requestedAt: string; remarks?: string | null
  requestedBy: { id: string; name: string; email?: string }; departmentTag?: Ref | null
  lines: Array<{ id: string }>; quantities?: Pick<Quantities, "required" | "reserved" | "allocated" | "remaining"> | null
}
type DemandDetail = Omit<DemandHeader, "lines"> & { lines: DemandLine[] }
type LinkableLine = {
  demandLineId: string; itemId: string; demandId: string; demandNo: string; requestedAt: string; state: string
  departmentName?: string | null; projectName?: string | null; requestedByName: string
  itemCode: string; itemTitle: string; specification?: string | null; unit: string
  required: string; reserved: string; allocated: string; remaining: string; backlog: string; pendingApproval: string
  ordered: string; shipped: string; physicalDeficit: string; unprocuredDeficit: string
}
type PurchaseDemandLink = {
  id: string; quantity: string
  demandLine: { id: string; title: string; unit: string; projectTag?: Ref | null; demand: { id: string; demandNo: string; state: string; departmentTag?: Ref | null; requestedBy: { name: string } } }
}
type PurchaseLine = {
  id: string; quantity: string; type: string; remarks?: string | null; item: Item
  demandLinks: PurchaseDemandLink[]; receiptLines: Array<{ quantity: string; receipt?: { receiptNo: string; postedAt: string } }>
}
type PurchaseHeader = {
  id: string; requestNo: string; status: string; createdAt?: string; updatedAt?: string; submittedAt?: string | null
  orderedAt?: string | null; shippedAt?: string | null; receivedAt?: string | null; vendor?: Ref | null
  trackingNumber?: string | null; boxNumber?: string | null; shippingDetails?: string | null; remarks?: string | null
  createdBy?: { id: string; name: string }; lines?: PurchaseLine[]
}
type Attachment = { id: string; kind: string; fileName: string; contentType: string; sizeBytes: number; createdAt: string; uploadedBy?: { name: string } }

const procurementTypes = ["FOREIGN_STANDARD", "FOREIGN_MANUFACTURED", "LOCAL_STANDARD", "LOCAL_MANUFACTURED"] as const
const purchaseStages = ["BACKLOG", "PENDING_APPROVAL", "ORDERED", "SHIPPED", "RECEIVED_IN_STORE"]
const procurementLabel = (value: string) => value.toLowerCase().replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase())
const statusLabel = (value: string) => ({ PENDING_APPROVAL: "Pending order approval", RECEIVED_IN_STORE: "Received in store", SUBMITTED: "Submitted" }[value] || procurementLabel(value))
const quantity = (value?: string | number | null) => Number(value || 0)
const formatQuantity = (value?: string | number | null) => new Intl.NumberFormat(undefined, { maximumFractionDigits: 6 }).format(quantity(value))
const formatDate = (value?: string | null) => value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(value)) : "—"

async function jsonFetch<T>(url: string, init?: RequestInit): Promise<T> {
  const response = await fetch(url, init)
  const body = await response.json().catch(() => ({})) as { error?: string }
  if (!response.ok) throw new Error(body.error || "Request failed")
  return body as T
}

async function loadCatalogue() {
  const items: Item[] = []
  let page = 1, totalPages = 1
  do {
    const response = await jsonFetch<{ items: Item[]; pagination?: { totalPages: number } }>(`/api/v1/items?page=${page}&pageSize=200&status=ACTIVE`)
    items.push(...response.items); totalPages = response.pagination?.totalPages || 1; page += 1
  } while (page <= totalPages)
  return items
}

function StatusBadge({ status }: { status: string }) {
  const tone = status === "RECEIVED_IN_STORE" || status === "CLOSED" || status === "ISSUED" ? "border-emerald-300 bg-emerald-50 text-emerald-800 dark:bg-emerald-950/30 dark:text-emerald-300"
    : status === "SHIPPED" ? "border-sky-300 bg-sky-50 text-sky-800 dark:bg-sky-950/30 dark:text-sky-300"
      : status === "ORDERED" || status === "ACTIVE" ? "border-blue-300 bg-blue-50 text-blue-800 dark:bg-blue-950/30 dark:text-blue-300"
        : status === "PENDING_APPROVAL" ? "border-amber-300 bg-amber-50 text-amber-800 dark:bg-amber-950/30 dark:text-amber-300"
          : status === "CANCELLED" ? "border-rose-300 bg-rose-50 text-rose-800 dark:bg-rose-950/30 dark:text-rose-300" : ""
  return <Badge variant="outline" className={cn("whitespace-nowrap font-medium", tone)}>{statusLabel(status)}</Badge>
}

function Metric({ label, value, emphasis }: { label: string; value: string | number | undefined; emphasis?: "danger" | "success" | "primary" }) {
  return <div className={cn("rounded-xl border bg-background px-3 py-2.5", emphasis === "danger" && "border-rose-200 bg-rose-50/50 dark:bg-rose-950/15", emphasis === "success" && "border-emerald-200 bg-emerald-50/50 dark:bg-emerald-950/15", emphasis === "primary" && "border-primary/25 bg-primary/[.04]")}> 
    <div className="text-[11px] font-semibold uppercase tracking-wide text-muted-foreground">{label}</div>
    <div className="mt-1 text-lg font-semibold tabular-nums">{formatQuantity(value)}</div>
  </div>
}

function EmptyState({ icon: Icon, title, description }: { icon: typeof ClipboardList; title: string; description: string }) {
  return <div className="flex flex-col items-center justify-center px-4 py-16 text-center"><div className="mb-4 rounded-2xl bg-muted p-4"><Icon className="size-7 text-muted-foreground"/></div><div className="font-semibold">{title}</div><p className="mt-1 max-w-md text-sm text-muted-foreground">{description}</p></div>
}

function SummaryCard({ icon: Icon, label, value, detail, tone = "default" }: { icon: typeof ClipboardList; label: string; value: string | number; detail: string; tone?: "default" | "amber" | "blue" | "emerald" }) {
  return <Card className={cn("overflow-hidden shadow-sm", tone === "amber" && "border-amber-200", tone === "blue" && "border-blue-200", tone === "emerald" && "border-emerald-200")}><CardContent className="flex items-center gap-4 p-5"><div className={cn("rounded-xl bg-muted p-3", tone === "amber" && "bg-amber-100 text-amber-700 dark:bg-amber-950/40", tone === "blue" && "bg-blue-100 text-blue-700 dark:bg-blue-950/40", tone === "emerald" && "bg-emerald-100 text-emerald-700 dark:bg-emerald-950/40")}><Icon className="size-5"/></div><div className="min-w-0"><div className="text-2xl font-semibold tabular-nums">{value}</div><div className="text-sm font-medium">{label}</div><div className="truncate text-xs text-muted-foreground">{detail}</div></div></CardContent></Card>
}

function DemandCreateDialog({ items, refs, onCreated }: { items: Item[]; refs: ReferenceData; onCreated: () => void }) {
  const [open, setOpen] = useState(false), [busy, setBusy] = useState(false), [selectedItemId, setSelectedItemId] = useState<string | null>(null)
  const [requestedTitle, setRequestedTitle] = useState(""), [categoryId, setCategoryId] = useState<string | null>(null), [discipline, setDiscipline] = useState<"MECHANICAL" | "ELECTRONICS" | null>(null)
  const [procurementType, setProcurementType] = useState("NOT_SPECIFIED")
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true)
    const form = new FormData(event.currentTarget), item = items.find(row => row.id === selectedItemId)
    try {
      await jsonFetch("/api/v1/demands", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({
        departmentTagId: form.get("departmentTagId") || null, remarks: form.get("remarks"), lines: [{ itemId: item?.id || null,
          title: item?.title || requestedTitle, description: form.get("description") || null, unit: item?.unit || form.get("unit") || "pcs",
          quantity: form.get("quantity"), suggestedCategoryId: item?.category?.id || categoryId,
          procurementType: procurementType === "NOT_SPECIFIED" ? null : procurementType,
          projectTagId: form.get("projectTagId") || null, vendorName: form.get("vendorName") || null,
        }],
      }) })
      toast.success("Demand submitted", { description: item ? `${item.code} — ${item.title}` : `${requestedTitle} will need catalogue reconciliation.` })
      setOpen(false); setSelectedItemId(null); setRequestedTitle(""); onCreated()
    } catch (error) { toast.error((error as Error).message) } finally { setBusy(false) }
  }
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button><Plus className="mr-2 size-4"/>New demand</Button></DialogTrigger><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>Submit a store demand</DialogTitle><DialogDescription>Request an existing component, or describe a new one for inventory reconciliation. Submission does not reserve or issue stock.</DialogDescription></DialogHeader><form className="space-y-5" onSubmit={submit}>
    <div className="grid gap-4 rounded-xl border bg-muted/20 p-4 sm:grid-cols-2"><div className="space-y-2"><Label>Department</Label><Select name="departmentTagId"><SelectTrigger><SelectValue placeholder="Select department"/></SelectTrigger><SelectContent>{refs.departments.map(row => <SelectItem key={row.id} value={row.id}>{row.name}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Project <span className="font-normal text-muted-foreground">(optional)</span></Label><Select name="projectTagId"><SelectTrigger><SelectValue placeholder="No project"/></SelectTrigger><SelectContent>{refs.projects.map(row => <SelectItem key={row.id} value={row.id}>{row.name}</SelectItem>)}</SelectContent></Select></div></div>
    <div className="space-y-2"><Label>Component</Label><ItemPicker items={items} categories={refs.itemCategories} value={selectedItemId} onValueChange={id => { setSelectedItemId(id); if (id) setRequestedTitle("") }} onRequestNew={(title, nextCategory, nextDiscipline) => { setSelectedItemId(null); setRequestedTitle(title); setCategoryId(nextCategory); setDiscipline(nextDiscipline) }}/>{requestedTitle && <div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm dark:bg-amber-950/20"><div className="font-medium">New component request: {requestedTitle}</div><div className="mt-1 text-xs text-muted-foreground">Inventory staff will reconcile this description before stock can be reserved.</div><input type="hidden" name="unit" value="pcs"/></div>}</div>
    <div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Required quantity</Label><Input name="quantity" type="number" min="0.000001" step="any" required/></div><div className="space-y-2"><Label>Preferred procurement type</Label><Select value={procurementType} onValueChange={setProcurementType}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="NOT_SPECIFIED">Not specified</SelectItem>{procurementTypes.map(type => <SelectItem key={type} value={type}>{procurementLabel(type)}</SelectItem>)}</SelectContent></Select></div></div>
    <div className="grid gap-4 sm:grid-cols-2"><div className="space-y-2"><Label>Suggested vendor <span className="font-normal text-muted-foreground">(optional)</span></Label><Input name="vendorName" placeholder="Vendor name"/></div><div className="space-y-2"><Label>Description / specification</Label><Input name="description" placeholder="Size, rating, material or other detail"/></div></div>
    <div className="space-y-2"><Label>Remarks</Label><Textarea name="remarks" placeholder="Purpose, required date or delivery notes"/></div>
    <DialogFooter><Button type="button" variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button disabled={busy || (!selectedItemId && !requestedTitle.trim())}>{busy && <Loader2 className="mr-2 size-4 animate-spin"/>}Submit demand</Button></DialogFooter>
  </form></DialogContent></Dialog>
}

function BulkDemandImport({ onDone }: { onDone: () => void }) {
  const [file, setFile] = useState<File | null>(null), [busy, setBusy] = useState(false)
  async function upload() { if (!file) return; setBusy(true); const form = new FormData(); form.set("file", file); try { await jsonFetch("/api/v1/demands/import", { method: "POST", body: form }); toast.success("Demand workbook imported"); setFile(null); onDone() } catch (error) { toast.error((error as Error).message) } finally { setBusy(false) } }
  return <Card className="border-dashed"><CardContent className="flex flex-col gap-4 p-5 md:flex-row md:items-center"><div className="flex flex-1 items-center gap-3"><div className="rounded-xl bg-muted p-3"><Upload className="size-5 text-muted-foreground"/></div><div><div className="text-sm font-semibold">Bulk demand workbook</div><div className="text-xs text-muted-foreground">One workbook creates one demand with a row for each requested component.</div></div></div><Input className="md:max-w-xs" type="file" accept=".xlsx" onChange={event => setFile(event.target.files?.[0] || null)}/><Button variant="outline" disabled={!file || busy} onClick={upload}>{busy ? <Loader2 className="mr-2 size-4 animate-spin"/> : <Upload className="mr-2 size-4"/>}Import</Button></CardContent></Card>
}

function PurchaseComposer({ open, onOpenChange, onCreated, initial }: { open: boolean; onOpenChange: (open: boolean) => void; onCreated: () => void; initial?: { item: Item; demandLineId: string; unprocuredDeficit: string } | null }) {
  const [items, setItems] = useState<Item[]>([]), [categories, setCategories] = useState<CatalogueCategory[]>([]), [busy, setBusy] = useState(false)
  const [selectedItemId, setSelectedItemId] = useState<string | null>(initial?.item.id || null), [newItemTitle, setNewItemTitle] = useState("")
  const [newDiscipline, setNewDiscipline] = useState<"MECHANICAL" | "ELECTRONICS" | null>(null), [newCategoryId, setNewCategoryId] = useState<string | null>(null)
  const [orderedQuantity, setOrderedQuantity] = useState(initial?.unprocuredDeficit || ""), [coverage, setCoverage] = useState<Record<string, string>>({})
  const [linkable, setLinkable] = useState<LinkableLine[]>([]), [loadingLines, setLoadingLines] = useState(false)
  useEffect(() => { if (!open) return; Promise.all([loadCatalogue(), jsonFetch<ReferenceData>("/api/v1/reference-data")]).then(([catalogue, refs]) => { setItems(catalogue); setCategories(refs.itemCategories) }).catch(error => toast.error(error.message)) }, [open])
  useEffect(() => { if (!open) return; setSelectedItemId(initial?.item.id || null); setOrderedQuantity(initial?.unprocuredDeficit || ""); setCoverage(initial ? { [initial.demandLineId]: initial.unprocuredDeficit } : {}) }, [open, initial])
  useEffect(() => { if (!open || !selectedItemId) { setLinkable([]); return }; setLoadingLines(true); jsonFetch<{ lines: LinkableLine[] }>(`/api/v1/demands/linkable?itemId=${selectedItemId}`).then(data => setLinkable(data.lines)).catch(error => toast.error(error.message)).finally(() => setLoadingLines(false)) }, [open, selectedItemId])
  const linkedQuantity = Object.values(coverage).reduce((sum, value) => sum + quantity(value), 0), replenishment = Math.max(quantity(orderedQuantity) - linkedQuantity, 0)
  function suggestCoverage() {
    let available = quantity(orderedQuantity); const next: Record<string, string> = {}
    for (const line of linkable) { const suggested = Math.min(available, quantity(line.unprocuredDeficit)); if (suggested > 0) { next[line.demandLineId] = String(suggested); available -= suggested } if (available <= 0) break }
    setCoverage(next)
  }
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const form = new FormData(event.currentTarget), item = items.find(row => row.id === selectedItemId)
    if (linkedQuantity > quantity(orderedQuantity)) return toast.error("Linked demand coverage cannot exceed the purchase quantity")
    setBusy(true)
    try {
      await jsonFetch("/api/v1/purchase-requests", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ vendorName: form.get("vendorName"), remarks: form.get("remarks"), trackingNumber: form.get("trackingNumber"), lines: [{ itemId: item?.id, type: form.get("type"), quantity: orderedQuantity,
        newItem: item ? undefined : { title: newItemTitle, specification: form.get("specification"), discipline: newDiscipline, categoryId: newCategoryId, unit: form.get("unit") || "pcs", manufacturerName: form.get("manufacturerName"), manufacturerPartNumber: form.get("manufacturerPartNumber") },
        demandLinks: Object.entries(coverage).filter(([, value]) => quantity(value) > 0).map(([demandLineId, value]) => ({ demandLineId, quantity: value })),
      }] }) })
      toast.success("Backlog purchase created", { description: linkedQuantity ? `${formatQuantity(linkedQuantity)} linked to demand; ${formatQuantity(replenishment)} for replenishment.` : "This purchase is store replenishment only." })
      onOpenChange(false); setCoverage({}); setSelectedItemId(null); setNewItemTitle(""); onCreated()
    } catch (error) { toast.error((error as Error).message) } finally { setBusy(false) }
  }
  const selectedItem = items.find(row => row.id === selectedItemId)
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[92vh] overflow-y-auto p-0 sm:max-w-4xl"><DialogHeader className="border-b px-6 py-5"><DialogTitle>Create backlog purchase</DialogTitle><DialogDescription>Set the total order quantity, then explicitly attribute some or all of it to open demand. Any remainder stays visible as general replenishment.</DialogDescription></DialogHeader><form onSubmit={submit}><div className="space-y-6 p-6">
    <div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label>Vendor</Label><Input name="vendorName" placeholder="Supplier name (optional)"/></div><div className="space-y-2"><Label>Procurement type</Label><Select name="type" defaultValue="LOCAL_STANDARD"><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{procurementTypes.map(type => <SelectItem key={type} value={type}>{procurementLabel(type)}</SelectItem>)}</SelectContent></Select></div></div>
    <div className="space-y-2"><Label>Component</Label><ItemPicker items={items} categories={categories} value={selectedItemId} onValueChange={id => { setSelectedItemId(id); setNewItemTitle(""); setCoverage({}) }} onRequestNew={(title, category, discipline) => { setSelectedItemId(null); setNewItemTitle(title); setNewCategoryId(category); setNewDiscipline(discipline); setCoverage({}) }}/></div>
    {newItemTitle && <div className="space-y-3 rounded-xl border border-amber-200 bg-amber-50/60 p-4 dark:bg-amber-950/20"><div><div className="font-semibold">Create incomplete component: {newItemTitle}</div><p className="text-xs text-muted-foreground">This purchase will be replenishment-only until the component is reconciled into the catalogue.</p></div><div className="grid gap-3 md:grid-cols-2"><Select value={newDiscipline || ""} onValueChange={value => setNewDiscipline(value as "MECHANICAL" | "ELECTRONICS")}><SelectTrigger><SelectValue placeholder="Discipline"/></SelectTrigger><SelectContent><SelectItem value="MECHANICAL">Mechanical</SelectItem><SelectItem value="ELECTRONICS">Electronics</SelectItem></SelectContent></Select><Select value={newCategoryId || "NONE"} onValueChange={value => setNewCategoryId(value === "NONE" ? null : value)}><SelectTrigger><SelectValue placeholder="Category"/></SelectTrigger><SelectContent><SelectItem value="NONE">Category not known</SelectItem>{categories.filter(row => !newDiscipline || row.discipline === newDiscipline).map(row => <SelectItem key={row.id} value={row.id}>{row.name}</SelectItem>)}</SelectContent></Select></div><Input name="specification" placeholder="Specification / size / rating"/><div className="grid gap-3 sm:grid-cols-3"><Input name="manufacturerName" placeholder="Manufacturer"/><Input name="manufacturerPartNumber" placeholder="Part number"/><Input name="unit" defaultValue="pcs" placeholder="Unit"/></div></div>}
    <div className="grid gap-4 md:grid-cols-[1fr_2fr]"><div className="space-y-2"><Label>Total purchase quantity</Label><Input value={orderedQuantity} onChange={event => setOrderedQuantity(event.target.value)} type="number" min="0.000001" step="any" required/><p className="text-xs text-muted-foreground">Includes linked demand and extra replenishment.</p></div><div className="grid grid-cols-2 gap-3"><Metric label="Linked to demand" value={linkedQuantity} emphasis="primary"/><Metric label="Store replenishment" value={replenishment} emphasis={replenishment > 0 ? "success" : undefined}/></div></div>
    {selectedItem && <div className="overflow-hidden rounded-xl border"><div className="flex flex-wrap items-center justify-between gap-3 border-b bg-muted/30 px-4 py-3"><div><div className="text-sm font-semibold">Demand coverage for {selectedItem.code}</div><div className="text-xs text-muted-foreground">Coverage is explicit and remains traceable to each demand row.</div></div><Button type="button" size="sm" variant="outline" disabled={!orderedQuantity || !linkable.some(row => quantity(row.unprocuredDeficit) > 0)} onClick={suggestCoverage}><Check className="mr-2 size-4"/>Suggest coverage</Button></div>
      {loadingLines ? <div className="flex items-center justify-center py-10 text-sm text-muted-foreground"><Loader2 className="mr-2 size-4 animate-spin"/>Loading open demand…</div> : linkable.length ? <div className="max-h-72 divide-y overflow-y-auto">{linkable.map(line => <div key={line.demandLineId} className="grid gap-3 p-4 md:grid-cols-[1fr_auto] md:items-center"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><span className="font-medium">{line.demandNo}</span><StatusBadge status={line.state}/><span className="text-xs text-muted-foreground">{line.projectName || line.departmentName || "No destination tag"}</span></div><div className="mt-1 text-xs text-muted-foreground">{line.requestedByName} · Remaining {formatQuantity(line.remaining)} · Physical deficit {formatQuantity(line.physicalDeficit)} · Already covered {formatQuantity(quantity(line.backlog) + quantity(line.pendingApproval) + quantity(line.ordered) + quantity(line.shipped))}</div></div><div className="flex items-center gap-2"><Label className="whitespace-nowrap text-xs">Link quantity</Label><Input className="w-28 text-right" type="number" min="0" step="any" max={line.unprocuredDeficit} value={coverage[line.demandLineId] || ""} onChange={event => setCoverage(current => ({ ...current, [line.demandLineId]: event.target.value }))} placeholder="0"/></div></div>)}</div> : <EmptyState icon={CheckCircle2} title="No open demand for this component" description="The purchase can still be created as general store replenishment."/>}
    </div>}
    <div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label>Tracking reference <span className="font-normal text-muted-foreground">(optional)</span></Label><Input name="trackingNumber" placeholder="Quote, RFQ or initial tracking reference"/></div><div className="space-y-2"><Label>Remarks</Label><Textarea name="remarks" placeholder="Commercial or procurement notes"/></div></div>
  </div><DialogFooter className="border-t bg-muted/15 px-6 py-4"><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><Button disabled={busy || (!selectedItemId && !newItemTitle.trim()) || quantity(orderedQuantity) <= 0 || linkedQuantity > quantity(orderedQuantity)}>{busy && <Loader2 className="mr-2 size-4 animate-spin"/>}Create backlog purchase</Button></DialogFooter></form></DialogContent></Dialog>
}

function QuantityActionDialog({ action, onClose, onDone }: { action: { kind: "reserve" | "release" | "allocate" | "return"; demandId: string; line: DemandLine } | null; onClose: () => void; onDone: () => void }) {
  const [busy, setBusy] = useState(false)
  if (!action) return null
  const currentAction = action
  const labels = { reserve: ["Reserve stock", "Protect physical stock for this demand"], release: ["Release reservation", "Return protected stock to shared availability"], allocate: ["Issue / hand over", "Post an immutable stock movement against this demand"], return: ["Return issued stock", "Post returned material back into store stock"] } as const
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget), amount = form.get("quantity"), remarks = form.get("remarks"), key = crypto.randomUUID()
    try {
      if (currentAction.kind === "reserve" || currentAction.kind === "release") await jsonFetch(`/api/v1/demands/lines/${currentAction.line.id}/${currentAction.kind}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ quantity: amount, remarks, idempotencyKey: key }) })
      else if (currentAction.kind === "allocate") await jsonFetch(`/api/v1/demands/${currentAction.demandId}/allocate`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ idempotencyKey: key, remarks, lines: [{ demandLineId: currentAction.line.id, quantity: amount }] }) })
      else { const allocation = currentAction.line.allocationLines.find(row => quantity(row.quantity) > row.returnLines.reduce((sum, returned) => sum + quantity(returned.quantity), 0)); if (!allocation) throw new Error("No issued quantity is available to return"); await jsonFetch("/api/v1/inventory/returns", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ idempotencyKey: key, remarks, lines: [{ allocationLineId: allocation.id, quantity: amount }] }) }) }
      toast.success(`${labels[currentAction.kind][0]} posted`); onClose(); onDone()
    } catch (error) { toast.error((error as Error).message) } finally { setBusy(false) }
  }
  const maximum = action.kind === "reserve" ? Math.max(quantity(action.line.quantities.remaining) - quantity(action.line.quantities.reserved), 0) : action.kind === "release" || action.kind === "allocate" ? quantity(action.line.quantities.reserved) : quantity(action.line.quantities.allocated)
  return <Dialog open onOpenChange={value => { if (!value) onClose() }}><DialogContent><DialogHeader><DialogTitle>{labels[action.kind][0]}</DialogTitle><DialogDescription>{labels[action.kind][1]} for {action.line.item?.code || action.line.title}.</DialogDescription></DialogHeader><form className="space-y-4" onSubmit={submit}><div className="rounded-lg border bg-muted/20 p-3 text-sm"><div className="flex justify-between"><span className="text-muted-foreground">Maximum available</span><span className="font-semibold tabular-nums">{formatQuantity(maximum)} {action.line.unit}</span></div></div><div className="space-y-2"><Label>Quantity</Label><Input name="quantity" type="number" min="0.000001" max={maximum} step="any" required autoFocus/></div><div className="space-y-2"><Label>Remarks <span className="font-normal text-muted-foreground">(optional)</span></Label><Textarea name="remarks"/></div><DialogFooter><Button type="button" variant="outline" onClick={onClose}>Cancel</Button><Button disabled={busy}>{busy && <Loader2 className="mr-2 size-4 animate-spin"/>}Post transaction</Button></DialogFooter></form></DialogContent></Dialog>
}

function DemandDetailSheet({ demandId, onClose, onChanged }: { demandId: string | null; onClose: () => void; onChanged: () => void }) {
  const role = useAuthStore(state => state.user?.role), canManage = role === "SUPER_ADMIN" || role === "INVENTORY_MANAGER"
  const [demand, setDemand] = useState<DemandDetail | null>(null), [loading, setLoading] = useState(false)
  const [action, setAction] = useState<{ kind: "reserve" | "release" | "allocate" | "return"; demandId: string; line: DemandLine } | null>(null)
  const [purchaseInitial, setPurchaseInitial] = useState<{ item: Item; demandLineId: string; unprocuredDeficit: string } | null>(null), [purchaseOpen, setPurchaseOpen] = useState(false)
  const load = useCallback(async () => { if (!demandId) return; setLoading(true); try { const data = await jsonFetch<{ demand: DemandDetail }>(`/api/v1/demands/${demandId}`); setDemand(data.demand) } catch (error) { toast.error((error as Error).message) } finally { setLoading(false) } }, [demandId])
  useEffect(() => { void load() }, [load])
  return <><Sheet open={Boolean(demandId)} onOpenChange={value => { if (!value) { setDemand(null); onClose() } }}><SheetContent className="w-full overflow-y-auto p-0 sm:max-w-6xl"><SheetHeader className="sticky top-0 z-10 border-b bg-background/95 px-6 py-5 backdrop-blur"><div className="flex flex-wrap items-start justify-between gap-3 pr-8"><div><div className="flex items-center gap-2"><SheetTitle className="text-xl">{demand?.demandNo || "Demand details"}</SheetTitle>{demand && <StatusBadge status={demand.state}/>}</div><SheetDescription className="mt-1">{demand ? `${demand.requestedBy.name} · ${demand.departmentTag?.name || "No department"} · ${formatDate(demand.requestedAt)}` : "Loading demand…"}</SheetDescription></div>{demand && <Button variant="outline" size="sm" onClick={load}><RefreshCw className="mr-2 size-4"/>Refresh</Button>}</div></SheetHeader>
    {loading && !demand ? <div className="flex justify-center py-24"><Loader2 className="size-7 animate-spin text-muted-foreground"/></div> : demand ? <div className="space-y-6 p-6"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Metric label="Required" value={demand.lines.reduce((sum, line) => sum + quantity(line.quantities.required), 0)}/><Metric label="Reserved" value={demand.lines.reduce((sum, line) => sum + quantity(line.quantities.reserved), 0)} emphasis="primary"/><Metric label="Issued" value={demand.lines.reduce((sum, line) => sum + quantity(line.quantities.allocated) - quantity(line.quantities.returned), 0)} emphasis="success"/><Metric label="Unprocured deficit" value={demand.lines.reduce((sum, line) => sum + quantity(line.quantities.unprocuredDeficit), 0)} emphasis="danger"/></div>
      {demand.remarks && <div className="rounded-xl border bg-muted/20 p-4"><div className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Demand remarks</div><p className="mt-1 text-sm">{demand.remarks}</p></div>}
      <div className="space-y-4"><div><h3 className="text-base font-semibold">Demand lines</h3><p className="text-sm text-muted-foreground">Fulfilment, physical stock, and purchase coverage are shown as separate facts.</p></div>{demand.lines.map(line => {
        const required = quantity(line.quantities.required), fulfilled = Math.max(quantity(line.quantities.allocated) - quantity(line.quantities.returned), 0), progress = required ? Math.min(100, fulfilled / required * 100) : 0
        return <Card key={line.id} className="overflow-hidden shadow-sm"><CardHeader className="border-b bg-muted/15 pb-4"><div className="flex flex-col justify-between gap-3 lg:flex-row lg:items-start"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><CardTitle className="text-base">{line.item?.code || "Unreconciled"} — {line.title}</CardTitle><StatusBadge status={line.quantities.fulfilmentFacet}/><Badge variant="secondary">{statusLabel(line.quantities.stockFacet)}</Badge></div><div className="mt-1 text-xs text-muted-foreground">{[line.item?.specification, line.projectTag?.name || demand.departmentTag?.name, line.procurementType ? procurementLabel(line.procurementType) : null, line.vendor?.name].filter(Boolean).join(" · ")}</div></div>{canManage && <div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" disabled={!line.item || quantity(line.quantities.remaining) <= quantity(line.quantities.reserved)} onClick={() => setAction({ kind: "reserve", demandId: demand.id, line })}>Reserve</Button><Button size="sm" variant="outline" disabled={quantity(line.quantities.reserved) <= 0} onClick={() => setAction({ kind: "release", demandId: demand.id, line })}>Release</Button><Button size="sm" disabled={quantity(line.quantities.reserved) <= 0} onClick={() => setAction({ kind: "allocate", demandId: demand.id, line })}>Issue</Button><Button size="sm" variant="secondary" disabled={quantity(line.quantities.allocated) <= 0} onClick={() => setAction({ kind: "return", demandId: demand.id, line })}>Return</Button>{line.item && quantity(line.quantities.unprocuredDeficit) > 0 && <Button size="sm" variant="outline" className="border-primary/30" onClick={() => { setPurchaseInitial({ item: line.item!, demandLineId: line.id, unprocuredDeficit: line.quantities.unprocuredDeficit }); setPurchaseOpen(true) }}><ShoppingCart className="mr-2 size-4"/>Create purchase</Button>}</div>}</div></CardHeader><CardContent className="space-y-5 p-5">
          <div><div className="mb-2 flex justify-between text-xs"><span className="text-muted-foreground">Issued progress</span><span className="font-medium">{formatQuantity(fulfilled)} of {formatQuantity(required)} {line.unit}</span></div><Progress value={progress}/></div>
          <div className="grid grid-cols-2 gap-2 sm:grid-cols-4 lg:grid-cols-8"><Metric label="Required" value={line.quantities.required}/><Metric label="Reserved" value={line.quantities.reserved}/><Metric label="Issued" value={line.quantities.allocated}/><Metric label="Remaining" value={line.quantities.remaining}/><Metric label="Backlog" value={line.quantities.backlog}/><Metric label="Approval" value={line.quantities.pendingApproval}/><Metric label="Ordered" value={line.quantities.ordered}/><Metric label="Shipped" value={line.quantities.shipped}/></div>
          <div className="grid gap-3 md:grid-cols-2"><div className="rounded-xl border border-rose-200 bg-rose-50/50 p-4 dark:bg-rose-950/15"><div className="text-xs font-semibold uppercase tracking-wide text-rose-700 dark:text-rose-300">Physical stock deficit</div><div className="mt-1 text-2xl font-semibold tabular-nums">{formatQuantity(line.quantities.physicalDeficit)} <span className="text-sm font-normal">{line.unit}</span></div></div><div className="rounded-xl border border-amber-200 bg-amber-50/50 p-4 dark:bg-amber-950/15"><div className="text-xs font-semibold uppercase tracking-wide text-amber-700 dark:text-amber-300">Still unprocured</div><div className="mt-1 text-2xl font-semibold tabular-nums">{formatQuantity(line.quantities.unprocuredDeficit)} <span className="text-sm font-normal">{line.unit}</span></div></div></div>
          <div><div className="mb-2 flex items-center gap-2 text-sm font-semibold"><Link2 className="size-4 text-primary"/>Linked purchases</div>{line.purchaseLinks.length ? <div className="grid gap-2">{line.purchaseLinks.map(link => { const purchase = link.purchaseRequestLine.purchaseRequest, received = link.purchaseRequestLine.receiptLines?.reduce((sum, row) => sum + quantity(row.quantity), 0) || 0; return <div key={link.id} className="flex flex-col justify-between gap-3 rounded-xl border bg-muted/10 p-3 sm:flex-row sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className="font-medium">{purchase.requestNo}</span><StatusBadge status={purchase.status}/></div><div className="mt-1 text-xs text-muted-foreground">{purchase.vendor?.name || "Vendor not assigned"} · Linked {formatQuantity(link.quantity)} {line.unit}{received ? ` · Purchase line received ${formatQuantity(received)}` : ""}</div></div><div className="text-xs text-muted-foreground">Updated {formatDate(purchase.updatedAt)}</div></div> })}</div> : <div className="rounded-xl border border-dashed p-4 text-sm text-muted-foreground">No purchase coverage is linked to this demand line.</div>}</div>
        </CardContent></Card>
      })}</div>
    </div> : null}
  </SheetContent></Sheet><QuantityActionDialog action={action} onClose={() => setAction(null)} onDone={() => { void load(); onChanged() }}/><PurchaseComposer open={purchaseOpen} onOpenChange={setPurchaseOpen} initial={purchaseInitial} onCreated={() => { void load(); onChanged() }}/></>
}

export function DemandsPage() {
  const user = useAuthStore(state => state.user)
  const [scope, setScope] = useState<"mine" | "all">("mine"), [demands, setDemands] = useState<DemandHeader[]>([]), [items, setItems] = useState<Item[]>([])
  const [refs, setRefs] = useState<ReferenceData>({ itemCategories: [], departments: [], projects: [], vendors: [] }), [selected, setSelected] = useState<string | null>(null)
  const [query, setQuery] = useState(""), [stateFilter, setStateFilter] = useState("OPEN"), [loading, setLoading] = useState(true)
  const load = useCallback(async () => { setLoading(true); try { const [demandData, catalogue, references] = await Promise.all([jsonFetch<{ demands: DemandHeader[] }>(`/api/v1/demands?mine=${scope === "mine"}`), loadCatalogue(), jsonFetch<ReferenceData>("/api/v1/reference-data")]); setDemands(demandData.demands); setItems(catalogue); setRefs(references) } catch (error) { toast.error((error as Error).message) } finally { setLoading(false) } }, [scope])
  useEffect(() => { void load() }, [load])
  const filtered = demands.filter(demand => (stateFilter === "ALL" || stateFilter === "OPEN" && ["SUBMITTED", "ACTIVE"].includes(demand.state) || demand.state === stateFilter) && (!query.trim() || `${demand.demandNo} ${demand.requestedBy.name} ${demand.departmentTag?.name || ""}`.toLowerCase().includes(query.trim().toLowerCase())))
  const totals = demands.reduce((result, demand) => ({ required: result.required + quantity(demand.quantities?.required), remaining: result.remaining + quantity(demand.quantities?.remaining), allocated: result.allocated + quantity(demand.quantities?.allocated) }), { required: 0, remaining: 0, allocated: 0 })
  return <div className="space-y-6"><PageHeader title="Demands" description="Track each request from submission through stock coverage, purchasing, issue and return." icon={ClipboardList}><div className="flex flex-wrap gap-2"><a href="/api/v1/demands/template"><Button variant="outline"><Download className="mr-2 size-4"/>Template</Button></a><DemandCreateDialog items={items} refs={refs} onCreated={load}/></div></PageHeader>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><SummaryCard icon={ClipboardList} label="Visible demands" value={demands.length} detail={scope === "mine" ? `Requested by ${user?.name || "you"}` : "Across all requesters"}/><SummaryCard icon={CircleDollarSign} label="Total required" value={formatQuantity(totals.required)} detail="Across the selected scope" tone="blue"/><SummaryCard icon={Warehouse} label="Issued" value={formatQuantity(totals.allocated)} detail="Posted stock handovers" tone="emerald"/><SummaryCard icon={PackageCheck} label="Remaining" value={formatQuantity(totals.remaining)} detail="Not yet fulfilled" tone="amber"/></div>
    <BulkDemandImport onDone={load}/>
    <Card className="overflow-hidden shadow-sm"><CardHeader className="border-b bg-muted/15"><div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-center"><div><CardTitle className="text-base">Demand register</CardTitle><p className="mt-1 text-sm text-muted-foreground">Choose exactly whose demands you want to see.</p></div><div className="inline-flex w-full rounded-lg border bg-background p-1 sm:w-auto"><Button className="flex-1 sm:min-w-32" size="sm" variant={scope === "mine" ? "default" : "ghost"} onClick={() => setScope("mine")}><UserRound className="mr-2 size-4"/>My Demands</Button><Button className="flex-1 sm:min-w-32" size="sm" variant={scope === "all" ? "default" : "ghost"} onClick={() => setScope("all")}><Building2 className="mr-2 size-4"/>All Demands</Button></div></div></CardHeader><CardContent className="p-0"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search demand number, requester or department…"/></div><Select value={stateFilter} onValueChange={setStateFilter}><SelectTrigger className="sm:w-48"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="OPEN">Open demands</SelectItem><SelectItem value="ALL">All statuses</SelectItem><SelectItem value="SUBMITTED">Submitted</SelectItem><SelectItem value="ACTIVE">Active</SelectItem><SelectItem value="CLOSED">Closed</SelectItem><SelectItem value="CANCELLED">Cancelled</SelectItem></SelectContent></Select></div>
      <div className="overflow-x-auto"><Table><TableHeader><TableRow className="bg-muted/25 hover:bg-muted/25"><TableHead className="pl-5">Demand</TableHead><TableHead>Requester / destination</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Required</TableHead><TableHead className="text-right">Reserved</TableHead><TableHead className="text-right">Issued</TableHead><TableHead className="text-right">Remaining</TableHead><TableHead className="pr-5"></TableHead></TableRow></TableHeader><TableBody>{filtered.map(demand => { const required = quantity(demand.quantities?.required), allocated = quantity(demand.quantities?.allocated); return <TableRow key={demand.id} className="group"><TableCell className="pl-5"><div className="font-semibold">{demand.demandNo}</div><div className="mt-0.5 text-xs text-muted-foreground">{demand.lines.length} component row{demand.lines.length === 1 ? "" : "s"} · {formatDate(demand.requestedAt)}</div></TableCell><TableCell><div className="font-medium">{demand.requestedBy.name}</div><div className="text-xs text-muted-foreground">{demand.departmentTag?.name || "No department tag"}</div></TableCell><TableCell><StatusBadge status={demand.state}/></TableCell><TableCell className="text-right tabular-nums">{formatQuantity(required)}</TableCell><TableCell className="text-right tabular-nums">{formatQuantity(demand.quantities?.reserved)}</TableCell><TableCell className="text-right"><div className="font-medium tabular-nums">{formatQuantity(allocated)}</div><Progress className="ml-auto mt-1 h-1.5 w-20" value={required ? allocated / required * 100 : 0}/></TableCell><TableCell className="text-right font-semibold tabular-nums">{formatQuantity(demand.quantities?.remaining)}</TableCell><TableCell className="pr-5 text-right"><Button size="sm" variant="ghost" onClick={() => setSelected(demand.id)}>View details<ChevronRight className="ml-1 size-4"/></Button></TableCell></TableRow>})}</TableBody></Table></div>{loading ? <div className="flex justify-center py-14"><Loader2 className="size-6 animate-spin text-muted-foreground"/></div> : !filtered.length && <EmptyState icon={ClipboardList} title={scope === "mine" ? "No matching demands from you" : "No matching demands"} description="Try another status or search, or submit a new demand."/>}
    </CardContent></Card><DemandDetailSheet demandId={selected} onClose={() => setSelected(null)} onChanged={load}/>
  </div>
}

function PurchaseTimeline({ request }: { request: PurchaseHeader }) {
  const current = purchaseStages.indexOf(request.status)
  return <div className="grid grid-cols-5 gap-1">{purchaseStages.map((stage, index) => <div key={stage} className="min-w-0"><div className={cn("h-1.5 rounded-full", index <= current ? "bg-primary" : "bg-muted")}/><div className={cn("mt-2 truncate text-[10px] font-medium sm:text-xs", index <= current ? "text-foreground" : "text-muted-foreground")}>{statusLabel(stage)}</div></div>)}</div>
}

function CoverageEditor({ requestId, line, onDone }: { requestId: string; line: PurchaseLine; onDone: () => void }) {
  const [open, setOpen] = useState(false), [linkable, setLinkable] = useState<LinkableLine[]>([]), [busy, setBusy] = useState(false)
  const [selectedDemandLineId, setSelectedDemandLineId] = useState(""), [amount, setAmount] = useState("")
  const linked = line.demandLinks.reduce((sum, row) => sum + quantity(row.quantity), 0), capacity = Math.max(quantity(line.quantity) - linked, 0)
  useEffect(() => { if (open) jsonFetch<{ lines: LinkableLine[] }>(`/api/v1/demands/linkable?itemId=${line.item.id}`).then(data => setLinkable(data.lines.filter(candidate => !line.demandLinks.some(existing => existing.demandLine.id === candidate.demandLineId)))).catch(error => toast.error(error.message)) }, [open, line])
  async function add() { setBusy(true); try { await jsonFetch(`/api/v1/purchase-requests/${requestId}/lines/${line.id}/demand-links`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ demandLineId: selectedDemandLineId, quantity: amount }) }); toast.success("Demand coverage added"); setOpen(false); onDone() } catch (error) { toast.error((error as Error).message) } finally { setBusy(false) } }
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm" variant="outline" disabled={capacity <= 0}><Plus className="mr-2 size-4"/>Link demand</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Link demand coverage</DialogTitle><DialogDescription>{formatQuantity(capacity)} {line.item.unit} remains available on this purchase line for attribution.</DialogDescription></DialogHeader><div className="space-y-4"><div className="space-y-2"><Label>Open demand row</Label><Select value={selectedDemandLineId} onValueChange={value => { setSelectedDemandLineId(value); const selected = linkable.find(row => row.demandLineId === value); setAmount(String(Math.min(capacity, quantity(selected?.unprocuredDeficit)))) }}><SelectTrigger><SelectValue placeholder="Select demand"/></SelectTrigger><SelectContent>{linkable.filter(row => quantity(row.unprocuredDeficit) > 0).map(row => <SelectItem key={row.demandLineId} value={row.demandLineId}>{row.demandNo} · {row.projectName || row.departmentName || row.requestedByName} · gap {formatQuantity(row.unprocuredDeficit)}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Coverage quantity</Label><Input type="number" min="0.000001" max={Math.min(capacity, quantity(linkable.find(row => row.demandLineId === selectedDemandLineId)?.unprocuredDeficit))} step="any" value={amount} onChange={event => setAmount(event.target.value)}/></div></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button disabled={busy || !selectedDemandLineId || quantity(amount) <= 0} onClick={add}>{busy && <Loader2 className="mr-2 size-4 animate-spin"/>}Add coverage</Button></DialogFooter></DialogContent></Dialog>
}

function PurchaseLineEditor({ requestId, line, onDone }: { requestId: string; line: PurchaseLine; onDone: () => void }) {
  const [open, setOpen] = useState(false), [busy, setBusy] = useState(false), [amount, setAmount] = useState(line.quantity)
  const linked = line.demandLinks.reduce((sum, row) => sum + quantity(row.quantity), 0)
  async function save() { setBusy(true); try { await jsonFetch(`/api/v1/purchase-requests/${requestId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ lineUpdates: [{ id: line.id, quantity: amount, remarks: line.remarks }] }) }); toast.success("Purchase quantity updated"); setOpen(false); onDone() } catch (error) { toast.error((error as Error).message) } finally { setBusy(false) } }
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm" variant="ghost">Edit quantity</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Edit purchase quantity</DialogTitle><DialogDescription>{line.item.code} — {line.item.title}. The total cannot be lower than its {formatQuantity(linked)} linked demand coverage.</DialogDescription></DialogHeader><div className="space-y-2"><Label>Total purchase quantity</Label><Input type="number" min={Math.max(linked, 0.000001)} step="any" value={amount} onChange={event => setAmount(event.target.value)} autoFocus/><div className="flex justify-between rounded-lg bg-muted/40 p-3 text-sm"><span>Replenishment remainder</span><span className="font-semibold tabular-nums">{formatQuantity(Math.max(quantity(amount) - linked, 0))} {line.item.unit}</span></div></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button disabled={busy || quantity(amount) < linked || quantity(amount) <= 0} onClick={save}>{busy && <Loader2 className="mr-2 size-4 animate-spin"/>}Save quantity</Button></DialogFooter></DialogContent></Dialog>
}

function CoverageLinkEditor({ requestId, link, unit, onDone }: { requestId: string; link: PurchaseDemandLink; unit: string; onDone: () => void }) {
  const [open, setOpen] = useState(false), [busy, setBusy] = useState(false), [amount, setAmount] = useState(link.quantity)
  async function save() { setBusy(true); try { await jsonFetch(`/api/v1/purchase-requests/${requestId}/demand-links/${link.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ quantity: amount }) }); toast.success("Demand coverage updated"); setOpen(false); onDone() } catch (error) { toast.error((error as Error).message) } finally { setBusy(false) } }
  return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><Button size="sm" variant="ghost">Edit</Button></DialogTrigger><DialogContent><DialogHeader><DialogTitle>Edit linked coverage</DialogTitle><DialogDescription>Update the explicit quantity attributed to {link.demandLine.demand.demandNo}.</DialogDescription></DialogHeader><div className="space-y-2"><Label>Coverage quantity ({unit})</Label><Input type="number" min="0.000001" step="any" value={amount} onChange={event => setAmount(event.target.value)} autoFocus/></div><DialogFooter><Button variant="outline" onClick={() => setOpen(false)}>Cancel</Button><Button disabled={busy || quantity(amount) <= 0} onClick={save}>{busy && <Loader2 className="mr-2 size-4 animate-spin"/>}Save coverage</Button></DialogFooter></DialogContent></Dialog>
}

function PurchaseDetailSheet({ purchaseId, onClose, onChanged }: { purchaseId: string | null; onClose: () => void; onChanged: () => void }) {
  const role = useAuthStore(state => state.user?.role), canManage = role === "SUPER_ADMIN" || role === "INVENTORY_MANAGER", canApprove = role === "SUPER_ADMIN" || role === "PURCHASE_APPROVER"
  const [request, setRequest] = useState<PurchaseHeader | null>(null), [attachments, setAttachments] = useState<Attachment[]>([]), [loading, setLoading] = useState(false), [busy, setBusy] = useState(false)
  const load = useCallback(async () => { if (!purchaseId) return; setLoading(true); try { const [detail, files] = await Promise.all([jsonFetch<{ request: PurchaseHeader }>(`/api/v1/purchase-requests/${purchaseId}`), jsonFetch<{ attachments: Attachment[] }>(`/api/v1/purchase-requests/${purchaseId}/attachments`)]); setRequest(detail.request); setAttachments(files.attachments) } catch (error) { toast.error((error as Error).message) } finally { setLoading(false) } }, [purchaseId])
  useEffect(() => { void load() }, [load])
  async function transition() { if (!request) return; const next: Record<string, string> = { BACKLOG: "PENDING_APPROVAL", PENDING_APPROVAL: "ORDERED", ORDERED: "SHIPPED" }, status = next[request.status]; if (!status) return; setBusy(true); try { await jsonFetch(`/api/v1/purchase-requests/${request.id}/transition`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status }) }); toast.success(`Purchase moved to ${statusLabel(status)}`); await load(); onChanged() } catch (error) { toast.error((error as Error).message) } finally { setBusy(false) } }
  async function saveMetadata(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!request) return; setBusy(true); const form = new FormData(event.currentTarget); try { await jsonFetch(`/api/v1/purchase-requests/${request.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify(Object.fromEntries(form)) }); toast.success("Purchase details updated"); await load(); onChanged() } catch (error) { toast.error((error as Error).message) } finally { setBusy(false) } }
  async function receive(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!request?.lines) return; const form = new FormData(event.currentTarget), lines = request.lines.map(line => ({ purchaseRequestLineId: line.id, quantity: form.get(`quantity-${line.id}`), unitCost: form.get(`cost-${line.id}`) || undefined })).filter(line => quantity(line.quantity as string) > 0); if (!lines.length) return toast.error("Enter at least one received quantity"); setBusy(true); try { await jsonFetch(`/api/v1/purchase-requests/${request.id}/receipts`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ idempotencyKey: crypto.randomUUID(), remarks: form.get("remarks"), lines }) }); toast.success("Goods receipt posted", { description: "Physical stock has been increased; demand allocation remains a separate action." }); await load(); onChanged() } catch (error) { toast.error((error as Error).message) } finally { setBusy(false) } }
  async function upload(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!request) return; const form = new FormData(event.currentTarget), file = form.get("file") as File; if (!file?.size) return toast.error("Select a file"); if (file.size > 5 * 1024 * 1024) return toast.error("File must not exceed 5 MB"); setBusy(true); try { await jsonFetch(`/api/v1/purchase-requests/${request.id}/attachments`, { method: "POST", body: form }); toast.success("Document attached"); await load() } catch (error) { toast.error((error as Error).message) } finally { setBusy(false) } }
  async function removeLink(linkId: string) { if (!request) return; setBusy(true); try { const response = await fetch(`/api/v1/purchase-requests/${request.id}/demand-links/${linkId}`, { method: "DELETE" }); if (!response.ok) { const body = await response.json(); throw new Error(body.error || "Could not remove coverage") }; toast.success("Demand coverage removed"); await load(); onChanged() } catch (error) { toast.error((error as Error).message) } finally { setBusy(false) } }
  const canAdvance = request && ((request.status === "PENDING_APPROVAL" && canApprove) || (["BACKLOG", "ORDERED"].includes(request.status) && canManage))
  return <Sheet open={Boolean(purchaseId)} onOpenChange={value => { if (!value) { setRequest(null); onClose() } }}><SheetContent className="w-full overflow-y-auto p-0 sm:max-w-6xl"><SheetHeader className="sticky top-0 z-10 border-b bg-background/95 px-6 py-5 backdrop-blur"><div className="flex flex-wrap items-start justify-between gap-3 pr-8"><div><div className="flex items-center gap-2"><SheetTitle className="text-xl">{request?.requestNo || "Purchase details"}</SheetTitle>{request && <StatusBadge status={request.status}/>}</div><SheetDescription className="mt-1">{request ? `${request.vendor?.name || "Vendor not assigned"} · Created ${formatDate(request.createdAt)}${request.createdBy ? ` by ${request.createdBy.name}` : ""}` : "Loading purchase…"}</SheetDescription></div><div className="flex gap-2">{canAdvance && <Button size="sm" onClick={transition} disabled={busy}>{request?.status === "PENDING_APPROVAL" ? <CheckCircle2 className="mr-2 size-4"/> : <ArrowRight className="mr-2 size-4"/>}{request?.status === "PENDING_APPROVAL" ? "Approve order" : request?.status === "ORDERED" ? "Mark shipped" : "Submit for approval"}</Button>}<Button size="sm" variant="outline" onClick={load}><RefreshCw className="size-4"/></Button></div></div></SheetHeader>
    {loading && !request ? <div className="flex justify-center py-24"><Loader2 className="size-7 animate-spin text-muted-foreground"/></div> : request?.lines ? <div className="space-y-6 p-6"><PurchaseTimeline request={request}/><div className="grid gap-3 sm:grid-cols-3"><Metric label="Purchase quantity" value={request.lines.reduce((sum, line) => sum + quantity(line.quantity), 0)} emphasis="primary"/><Metric label="Linked demand" value={request.lines.reduce((sum, line) => sum + line.demandLinks.reduce((linkSum, link) => linkSum + quantity(link.quantity), 0), 0)}/><Metric label="Store replenishment" value={request.lines.reduce((sum, line) => sum + quantity(line.quantity) - line.demandLinks.reduce((linkSum, link) => linkSum + quantity(link.quantity), 0), 0)} emphasis="success"/></div>
      <Tabs defaultValue="coverage"><TabsList className="grid h-auto w-full grid-cols-2 sm:grid-cols-4"><TabsTrigger value="coverage"><Link2/>Demand coverage</TabsTrigger><TabsTrigger value="receiving"><PackageCheck/>Receiving</TabsTrigger><TabsTrigger value="shipping"><Ship/>Vendor & shipping</TabsTrigger><TabsTrigger value="documents"><Paperclip/>Documents</TabsTrigger></TabsList>
        <TabsContent value="coverage" className="space-y-4 pt-3">{request.lines.map(line => { const linked = line.demandLinks.reduce((sum, link) => sum + quantity(link.quantity), 0), received = line.receiptLines.reduce((sum, receipt) => sum + quantity(receipt.quantity), 0); return <Card key={line.id}><CardHeader className="border-b bg-muted/15"><div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-start"><div><CardTitle className="text-base">{line.item.code} — {line.item.title}</CardTitle><p className="mt-1 text-xs text-muted-foreground">{[line.item.specification, procurementLabel(line.type)].filter(Boolean).join(" · ")}</p></div>{request.status === "BACKLOG" && canManage && <div className="flex gap-2"><PurchaseLineEditor requestId={request.id} line={line} onDone={() => { void load(); onChanged() }}/><CoverageEditor requestId={request.id} line={line} onDone={() => { void load(); onChanged() }}/></div>}</div></CardHeader><CardContent className="space-y-4 p-5"><div className="grid grid-cols-2 gap-2 sm:grid-cols-4"><Metric label="Purchase" value={line.quantity}/><Metric label="Linked" value={linked} emphasis="primary"/><Metric label="Replenishment" value={quantity(line.quantity) - linked} emphasis="success"/><Metric label="Received" value={received}/></div>{line.demandLinks.length ? <div className="space-y-2">{line.demandLinks.map(link => <div key={link.id} className="flex flex-col justify-between gap-3 rounded-xl border p-3 sm:flex-row sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className="font-semibold">{link.demandLine.demand.demandNo}</span><StatusBadge status={link.demandLine.demand.state}/></div><div className="mt-1 text-xs text-muted-foreground">{link.demandLine.projectTag?.name || link.demandLine.demand.departmentTag?.name || "No destination"} · Requested by {link.demandLine.demand.requestedBy.name}</div></div><div className="flex items-center gap-2"><div className="text-right"><div className="font-semibold tabular-nums">{formatQuantity(link.quantity)} {line.item.unit}</div><div className="text-[11px] text-muted-foreground">explicit coverage</div></div>{request.status === "BACKLOG" && canManage && <><CoverageLinkEditor requestId={request.id} link={link} unit={line.item.unit} onDone={() => { void load(); onChanged() }}/><Button size="icon" variant="ghost" disabled={busy} onClick={() => removeLink(link.id)} aria-label="Remove demand coverage"><Trash2 className="size-4 text-muted-foreground"/></Button></>}</div></div>)}</div> : <div className="rounded-xl border border-dashed p-5 text-center text-sm text-muted-foreground">This line is replenishment-only. No demand coverage is linked.</div>}</CardContent></Card>})}</TabsContent>
        <TabsContent value="receiving" className="pt-3">{["ORDERED", "SHIPPED"].includes(request.status) && canManage ? <Card><CardHeader><CardTitle className="text-base">Post goods receipt</CardTitle><p className="text-sm text-muted-foreground">Enter any quantities received now. Partial and repeated receipts are supported.</p></CardHeader><CardContent><form className="space-y-4" onSubmit={receive}><div className="space-y-3">{request.lines.map(line => { const received = line.receiptLines.reduce((sum, row) => sum + quantity(row.quantity), 0), remaining = quantity(line.quantity) - received; return <div key={line.id} className="grid gap-3 rounded-xl border p-4 md:grid-cols-[1fr_9rem_9rem] md:items-end"><div><div className="font-medium">{line.item.code} — {line.item.title}</div><div className="text-xs text-muted-foreground">Ordered {formatQuantity(line.quantity)} · Received {formatQuantity(received)} · Remaining {formatQuantity(remaining)} {line.item.unit}</div></div><div className="space-y-2"><Label className="text-xs">Receive now</Label><Input name={`quantity-${line.id}`} type="number" min="0" max={remaining} step="any" placeholder="0"/></div><div className="space-y-2"><Label className="text-xs">Unit cost</Label><Input name={`cost-${line.id}`} type="number" min="0" step="any" placeholder="Optional"/></div></div>})}</div><div className="space-y-2"><Label>Receipt remarks</Label><Textarea name="remarks" placeholder="Delivery note, inspection note or discrepancy"/></div><div className="rounded-lg border border-blue-200 bg-blue-50/50 p-3 text-xs text-blue-800 dark:bg-blue-950/20 dark:text-blue-300">Posting a receipt increases physical stock. It does not silently allocate the stock to linked demands.</div><Button disabled={busy}>{busy && <Loader2 className="mr-2 size-4 animate-spin"/>}<PackageCheck className="mr-2 size-4"/>Post receipt</Button></form></CardContent></Card> : <Card><CardContent><EmptyState icon={PackageCheck} title={request.status === "RECEIVED_IN_STORE" ? "Purchase fully received" : "Not ready for receiving"} description={request.status === "RECEIVED_IN_STORE" ? "Every purchase line has been received into store." : "Receiving becomes available after the order is approved."}/></CardContent></Card>}</TabsContent>
        <TabsContent value="shipping" className="pt-3"><Card><CardHeader><CardTitle className="text-base">Vendor and shipping details</CardTitle><p className="text-sm text-muted-foreground">These details may be completed progressively as procurement advances.</p></CardHeader><CardContent><form className="space-y-4" onSubmit={saveMetadata}><div className="grid gap-4 sm:grid-cols-3"><div className="space-y-2"><Label>Vendor</Label><Input name="vendorName" defaultValue={request.vendor?.name || ""} disabled={!canManage}/></div><div className="space-y-2"><Label>Tracking number</Label><Input name="trackingNumber" defaultValue={request.trackingNumber || ""} disabled={!canManage}/></div><div className="space-y-2"><Label>Box number</Label><Input name="boxNumber" defaultValue={request.boxNumber || ""} disabled={!canManage}/></div></div><div className="space-y-2"><Label>Shipping details</Label><Textarea name="shippingDetails" defaultValue={request.shippingDetails || ""} disabled={!canManage} placeholder="Carrier, route, ETA or collection details"/></div><div className="space-y-2"><Label>Purchase remarks</Label><Textarea name="remarks" defaultValue={request.remarks || ""} disabled={!canManage}/></div>{canManage && <Button disabled={busy}>{busy && <Loader2 className="mr-2 size-4 animate-spin"/>}Save details</Button>}</form></CardContent></Card></TabsContent>
        <TabsContent value="documents" className="space-y-4 pt-3">{canManage && <Card><CardHeader><CardTitle className="text-base">Attach supporting document</CardTitle><p className="text-sm text-muted-foreground">PDF, PNG, JPG or XLSX up to 5 MB.</p></CardHeader><CardContent><form className="flex flex-col gap-3 sm:flex-row sm:items-end" onSubmit={upload}><div className="flex-1 space-y-2"><Label>File</Label><Input name="file" type="file" accept=".pdf,.png,.jpg,.jpeg,.xlsx" required/></div><div className="space-y-2 sm:w-48"><Label>Document type</Label><Select name="kind" defaultValue="QUOTATION"><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["QUOTATION", "INVOICE", "SHIPPING_DOCUMENT", "RECEIPT", "OTHER"].map(kind => <SelectItem key={kind} value={kind}>{statusLabel(kind)}</SelectItem>)}</SelectContent></Select></div><Button disabled={busy}><Upload className="mr-2 size-4"/>Upload</Button></form></CardContent></Card>}<Card><CardContent className="p-0">{attachments.length ? <div className="divide-y">{attachments.map(file => <a key={file.id} href={`/api/v1/purchase-requests/${request.id}/attachments/${file.id}`} className="flex items-center gap-3 p-4 transition-colors hover:bg-muted/30"><div className="rounded-lg bg-muted p-2"><FileText className="size-5"/></div><div className="min-w-0 flex-1"><div className="truncate text-sm font-medium">{file.fileName}</div><div className="text-xs text-muted-foreground">{statusLabel(file.kind)} · {(file.sizeBytes / 1024).toFixed(1)} KB · {formatDate(file.createdAt)}{file.uploadedBy ? ` · ${file.uploadedBy.name}` : ""}</div></div><Download className="size-4 text-muted-foreground"/></a>)}</div> : <EmptyState icon={Paperclip} title="No documents attached" description="Quotations, invoices and shipping documents will appear here."/>}</CardContent></Card></TabsContent>
      </Tabs>
    </div> : null}
  </SheetContent></Sheet>
}

export function PurchasingPage() {
  const role = useAuthStore(state => state.user?.role), canManage = role === "SUPER_ADMIN" || role === "INVENTORY_MANAGER"
  const [requests, setRequests] = useState<PurchaseHeader[]>([]), [loading, setLoading] = useState(true), [composerOpen, setComposerOpen] = useState(false), [selected, setSelected] = useState<string | null>(null)
  const [query, setQuery] = useState(""), [status, setStatus] = useState("ACTIVE")
  const load = useCallback(async () => { setLoading(true); try { const data = await jsonFetch<{ requests: PurchaseHeader[] }>("/api/v1/purchase-requests"); setRequests(data.requests) } catch (error) { toast.error((error as Error).message) } finally { setLoading(false) } }, [])
  useEffect(() => { void load() }, [load])
  const filtered = requests.filter(request => (status === "ALL" || status === "ACTIVE" && request.status !== "RECEIVED_IN_STORE" || request.status === status) && (!query.trim() || `${request.requestNo} ${request.vendor?.name || ""} ${request.lines?.map(line => `${line.item.code} ${line.item.title} ${line.demandLinks.map(link => link.demandLine.demand.demandNo).join(" ")}`).join(" ") || ""}`.toLowerCase().includes(query.trim().toLowerCase())))
  const active = requests.filter(request => request.status !== "RECEIVED_IN_STORE"), pending = requests.filter(request => request.status === "PENDING_APPROVAL"), inTransit = requests.filter(request => request.status === "SHIPPED")
  const activeLinked = active.reduce((sum, request) => sum + (request.lines || []).reduce((lineSum, line) => lineSum + line.demandLinks.reduce((linkSum, link) => linkSum + quantity(link.quantity), 0), 0), 0)
  return <div className="space-y-6"><PageHeader title="Purchasing" description="Create orders from deficits, preserve demand traceability, and keep replenishment visibly separate." icon={ShoppingCart}>{canManage && <Button onClick={() => setComposerOpen(true)}><Plus className="mr-2 size-4"/>New purchase</Button>}</PageHeader>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><SummaryCard icon={ShoppingCart} label="Active purchases" value={active.length} detail="Backlog through shipped"/><SummaryCard icon={CheckCircle2} label="Awaiting approval" value={pending.length} detail="Purchase approver action required" tone="amber"/><SummaryCard icon={Ship} label="In transit" value={inTransit.length} detail="Marked as shipped" tone="blue"/><SummaryCard icon={Link2} label="Linked demand" value={formatQuantity(activeLinked)} detail="Active explicit coverage" tone="emerald"/></div>
    <Card className="overflow-hidden shadow-sm"><CardHeader className="border-b bg-muted/15"><div><CardTitle className="text-base">Purchase register</CardTitle><p className="mt-1 text-sm text-muted-foreground">Every row shows ordered quantity, linked demand coverage, and extra store replenishment.</p></div></CardHeader><CardContent className="p-0"><div className="flex flex-col gap-3 border-b p-4 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" value={query} onChange={event => setQuery(event.target.value)} placeholder="Search purchase, vendor, component or linked demand…"/></div><Select value={status} onValueChange={setStatus}><SelectTrigger className="sm:w-52"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="ACTIVE">Active purchases</SelectItem><SelectItem value="ALL">All statuses</SelectItem>{purchaseStages.map(stage => <SelectItem key={stage} value={stage}>{statusLabel(stage)}</SelectItem>)}</SelectContent></Select></div>
      <div className="overflow-x-auto"><Table><TableHeader><TableRow className="bg-muted/25 hover:bg-muted/25"><TableHead className="pl-5">Purchase</TableHead><TableHead>Vendor</TableHead><TableHead>Status</TableHead><TableHead>Components / demand</TableHead><TableHead className="text-right">Purchase</TableHead><TableHead className="text-right">Linked</TableHead><TableHead className="text-right">Replenishment</TableHead><TableHead className="pr-5"></TableHead></TableRow></TableHeader><TableBody>{filtered.map(request => { const total = (request.lines || []).reduce((sum, line) => sum + quantity(line.quantity), 0), linked = (request.lines || []).reduce((sum, line) => sum + line.demandLinks.reduce((linkSum, link) => linkSum + quantity(link.quantity), 0), 0); return <TableRow key={request.id}><TableCell className="pl-5"><div className="font-semibold">{request.requestNo}</div><div className="text-xs text-muted-foreground">{formatDate(request.createdAt)}</div></TableCell><TableCell>{request.vendor?.name || <span className="text-muted-foreground">Not assigned</span>}</TableCell><TableCell><StatusBadge status={request.status}/></TableCell><TableCell><div className="max-w-md text-sm font-medium">{request.lines?.map(line => `${line.item.code} — ${line.item.title}`).join(", ")}</div><div className="mt-0.5 text-xs text-muted-foreground">{Array.from(new Set(request.lines?.flatMap(line => line.demandLinks.map(link => link.demandLine.demand.demandNo)) || [])).join(", ") || "Replenishment only"}</div></TableCell><TableCell className="text-right font-medium tabular-nums">{formatQuantity(total)}</TableCell><TableCell className="text-right tabular-nums text-primary">{formatQuantity(linked)}</TableCell><TableCell className="text-right tabular-nums text-emerald-700 dark:text-emerald-400">{formatQuantity(total - linked)}</TableCell><TableCell className="pr-5 text-right"><Button variant="ghost" size="sm" onClick={() => setSelected(request.id)}>View details<ChevronRight className="ml-1 size-4"/></Button></TableCell></TableRow>})}</TableBody></Table></div>{loading ? <div className="flex justify-center py-14"><Loader2 className="size-6 animate-spin text-muted-foreground"/></div> : !filtered.length && <EmptyState icon={ShoppingCart} title="No matching purchases" description="Try another status or search, or create a new backlog purchase."/>}
    </CardContent></Card><PurchaseComposer open={composerOpen} onOpenChange={setComposerOpen} onCreated={load}/><PurchaseDetailSheet purchaseId={selected} onClose={() => setSelected(null)} onChanged={load}/>
  </div>
}
